<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Causa_Sel</name>
   <tag></tag>
   <elementGuidId>6962f6f1-f919-412c-a09d-e0819d87ef76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Sel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Sel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0be6dff5-faa5-45b1-869a-771bda5183c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>CHECKBOX</value>
      <webElementGuid>f689a55c-cb7c-4992-b54f-c460ee0e5efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Sel</value>
      <webElementGuid>78b7e6b9-b939-47c7-82f0-aefee8235242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sel</value>
      <webElementGuid>32fb30b9-0da3-4c17-99b6-0b8e42710c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>705bde56-8381-4a3b-8e89-c2fb7ca01540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2454867e-bea5-41f9-b79c-30eee78efd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>marrArray[this.value].Sel=this.checked;InsCheckSelClick(this,2,0,0);</value>
      <webElementGuid>a2cd96a8-bc8d-4d4d-adcc-35e231968b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[@class=&quot;grddata&quot;]/tbody[1]/tr[@id=&quot;gridmarrArray&quot;]/td[1]/input[@id=&quot;Sel&quot;]</value>
      <webElementGuid>3e89b1e3-5a16-473e-b02f-34095fa61aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Recargosdescuentosimpuestos - Pliza individualcertif/frame_BODY1</value>
      <webElementGuid>fcad7df5-a216-4a36-bae9-38cb7678ff00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Sel']</value>
      <webElementGuid>fb834e88-2d72-4834-a3c0-797ab6777c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='gridmarrArray']/td/input</value>
      <webElementGuid>cce5e905-75bc-48bc-bde3-7dc8926e244c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>1c4319a8-0eae-4951-b5fc-74de4dc310db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'CHECKBOX' and @id = 'Sel' and @name = 'Sel']</value>
      <webElementGuid>13cd9533-8169-4be2-bd18-3855de46689f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
