<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Convenio de cobranza_Add</name>
   <tag></tag>
   <elementGuidId>e06f9a14-0262-4bf2-a44f-09ea54434b4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cmdAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cmdAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a6efed99-11f4-4210-95c2-01e08a5b36cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>51c479ff-9563-4a16-a504-a2c5af354198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnLargeAddOn.png</value>
      <webElementGuid>70d8614c-51e0-436e-8ad0-e407f1a8bae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cmdAdd</value>
      <webElementGuid>5cba47e2-f900-468c-a967-bd49e70b02a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmdAdd</value>
      <webElementGuid>ad758be5-b56b-4768-aba0-e7c8064d593d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Agregar</value>
      <webElementGuid>06a8f6b3-b894-44ad-a09b-53855f17b18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Agregar</value>
      <webElementGuid>c126637c-1576-4dd0-a48f-e99802b35c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>MouseMoveImage(this, true)</value>
      <webElementGuid>d8a155ce-b7c8-4067-89cb-7e64d97ccb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>MouseMoveImage(this, false)</value>
      <webElementGuid>8a1901d1-db63-4719-b352-b7e9ffb49fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ToolbarHeaderHover</value>
      <webElementGuid>9d9e56d1-9863-42d9-9461-704721dd4289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmdAdd&quot;)</value>
      <webElementGuid>55524357-14dd-4c21-9377-3dfa3f6ba6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Intermediarios - Productores/frame_BODY            PEsta pgina utiliza frame, pero su BROWSER no lo soportaP        BODY_fraFolder</value>
      <webElementGuid>0c76a5f7-bde0-4c55-b9ea-3fce110bbbb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cmdAdd']</value>
      <webElementGuid>154aa76e-1790-41c8-a364-4427f650a520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CA024']/div[2]/a/img</value>
      <webElementGuid>1b680f98-d557-4c25-a90c-0f0d0f1f5af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Agregar']</value>
      <webElementGuid>79482b2e-232b-4ba6-8874-421a40bf7362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>b38a9331-23de-4933-8f98-6fa9c5758790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnLargeAddOn.png' and @name = 'cmdAdd' and @id = 'cmdAdd' and @alt = 'Agregar' and @title = 'Agregar']</value>
      <webElementGuid>fa8e428c-5021-444d-abbf-7406602a989b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
