<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODY            PEsta pgina utiliza frame, pero su BROWSER no lo soportaP        BODY_fraHeader</name>
   <tag></tag>
   <elementGuidId>0a3f5a3f-6fef-40ba-a9cc-fb478f50f5e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraHeader&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>a1bc955a-f25b-4f67-8044-c8a812fff198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraHeader</value>
      <webElementGuid>02ff3055-d0d4-4fe9-aedb-267aaf3c4a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>13524b49-20c5-451b-9132-1b9e16a09f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f782f295-af5f-4deb-8057-a50aeb910f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>32306a66-0fb6-4e06-bf71-38026ef7a172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Policy/PolicySeq/CA001_K.aspx?sConfig=InSequence&amp;LoadWithAction=&amp;bMenu=1&amp;sCodispl=CA001</value>
      <webElementGuid>e95e0cfe-5451-4146-b2f9-ee84499038f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[2]/frame[1]</value>
      <webElementGuid>f865e7b1-2120-473d-a673-00f8a92f07fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraHeader']</value>
      <webElementGuid>01be96ce-6585-4da7-a88b-cffd4081b9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset[2]/frame</value>
      <webElementGuid>287ac802-eef2-412c-bc3d-b086aa07127c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraHeader' and @src = '../Policy/PolicySeq/CA001_K.aspx?sConfig=InSequence&amp;LoadWithAction=&amp;bMenu=1&amp;sCodispl=CA001']</value>
      <webElementGuid>f9f98aab-5e4e-4be1-8640-49a1f67ae878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
