<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_FraHeader</name>
   <tag></tag>
   <elementGuidId>f2b5598d-54c9-4877-81f0-7e1a2c30a5ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraHeader&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>d9497975-7ef1-4300-b897-0489890afcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraHeader</value>
      <webElementGuid>f40fe430-e3a5-4803-805e-0bd37dbb2487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>840242bd-5ad2-4c9c-99e5-5877fb60da63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f826dc5b-1d92-43a9-9c4e-9a70d7b22d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>5747dd27-8e74-4c81-b565-38d76104a0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Policy/PolicySeq/CA001_K.aspx?sConfig=&amp;LoadWithAction=&amp;nHeight=130&amp;sCodisp=CA001&amp;sWindowDescript=Tratamiento+de+p%f3lizas&amp;nWindowTy=2&amp;sCodispl=CA001</value>
      <webElementGuid>cf350fc6-2b25-4362-ae5d-ec6e106f8930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[2]/frame[1]</value>
      <webElementGuid>02506ac7-d3e5-42a2-9601-5826c11897ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraHeader']</value>
      <webElementGuid>5c6d96e5-c5ef-49cc-9878-066542907d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset[2]/frame</value>
      <webElementGuid>7c6e0888-f60a-4f1b-8ece-86f0a238f2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraHeader' and @src = '../Policy/PolicySeq/CA001_K.aspx?sConfig=&amp;LoadWithAction=&amp;nHeight=130&amp;sCodisp=CA001&amp;sWindowDescript=Tratamiento+de+p%f3lizas&amp;nWindowTy=2&amp;sCodispl=CA001']</value>
      <webElementGuid>aacf65cf-eae1-4321-a9af-ec115bb5393a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
