<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_00000042933160</name>
   <tag></tag>
   <elementGuidId>6185bd3c-ca7c-42a8-b271-243daebf004b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;RecordFound(0,'tctClient','tctClient_Name');CloseWindow();; return false&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>533a1ead-7b66-4e4a-8be5-ccebd1ea2304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>JAVASCRIPT:</value>
      <webElementGuid>5a258cdc-8861-4a66-8b5b-e21ffe6e2ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>RecordFound(0,'tctClient','tctClient_Name');CloseWindow();; return false</value>
      <webElementGuid>068eab9f-1e94-478c-8cf4-5b41c3c7092a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00000042933160</value>
      <webElementGuid>23133d95-e997-40dc-9422-9189bf363ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[@class=&quot;grddata&quot;]/tbody[1]/tr[@id=&quot;gridmarrArray&quot;]/td[1]/label[@class=&quot;FIELD&quot;]/a[1]</value>
      <webElementGuid>6c427312-8b03-431d-a42b-0c8abb947225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;RecordFound(0,'tctClient','tctClient_Name');CloseWindow();; return false&quot;]</value>
      <webElementGuid>8d8ac082-e3a2-4bf5-accb-da7bfbe71327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='gridmarrArray']/td/label/a</value>
      <webElementGuid>c81fe2d8-987a-4e54-86c9-a99b256d3ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'00000042933160')]</value>
      <webElementGuid>a8f3f62e-35b5-497b-9a62-1602a5614489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orden'])[1]/following::a[1]</value>
      <webElementGuid>6ae5f34b-b523-44dc-84bf-8668a75a79d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre'])[1]/following::a[1]</value>
      <webElementGuid>d5c87c21-b31e-4c8f-8a85-2fb2ade3e5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contratante'])[1]/preceding::a[1]</value>
      <webElementGuid>8280f72a-93b2-4acc-9c03-7f140ae0ac44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allo , Camdela'])[1]/preceding::a[1]</value>
      <webElementGuid>94d38718-639f-4c9e-89d8-bfa1a6594f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='00000042933160']/parent::*</value>
      <webElementGuid>715d43c6-db32-4fc5-9f1a-54240da6a59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'JAVASCRIPT:')]</value>
      <webElementGuid>4ff781ab-eb41-4ba1-8368-69f5d00bee9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>219d8992-ea46-411c-911f-2a62106cc221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'JAVASCRIPT:' and (text() = '00000042933160' or . = '00000042933160')]</value>
      <webElementGuid>031746d0-bc52-427d-b2d3-d87243c2c5a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
