<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODY  PEsta pgina usa marcos, pero su_3d6ef9_1</name>
   <tag></tag>
   <elementGuidId>ad0ad5e8-7138-4c6c-993b-baefe1e7f3d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>72f67b36-0c69-4adb-89e9-0cd1e3bcee1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>framespacing</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>24e0c4dc-b7dd-4ded-a6e3-d3be538c7868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>6d54818d-84c1-4508-90d2-e95fdb8a7dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>1fb7ac77-ee12-4c4c-95d5-abab38114778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8695bf50-ef6e-42fa-987d-6fd15eeecd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraGeneric</value>
      <webElementGuid>45271b52-086c-461e-810e-60d3512d803b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=3&amp;nMainAction=0&amp;sCodispl=CA025&amp;nRole=65&amp;sClient=&amp;nCoverPos=-32768&amp;sSmoking=&amp;sCodisp=CA025&amp;sWindowDescript=Asegurables&amp;nWindowTy=9</value>
      <webElementGuid>fe87af71-c0db-4f85-a5d1-fd3eef1497c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>f90bcd0b-9b96-4bbd-8c52-36a2edbbba48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>d0e96fb3-b883-4c51-a000-1d591dd2f358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>d2531380-65fe-4f49-9690-30d007111114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=3&amp;nMainAction=0&amp;sCodispl=CA025&amp;nRole=65&amp;sClient=&amp;nCoverPos=-32768&amp;sSmoking=&amp;sCodisp=CA025&amp;sWindowDescript=Asegurables&amp;nWindowTy=9']</value>
      <webElementGuid>ea4a8bee-9adf-4cf4-a68a-fd43c889ebf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
