<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Razn Social a imprimir_cmdAccept (1)</name>
   <tag></tag>
   <elementGuidId>2ff7dcc1-c830-480b-9560-316c42f19a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cmdAccept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cmdAccept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c23a07a5-09a5-49ae-bedc-153d2b721c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6afbea62-2bc0-4e5d-b459-68af0f0fa965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnAcceptOn.png</value>
      <webElementGuid>7c507d8b-6308-497f-89e0-297b9dfd633a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cmdAccept</value>
      <webElementGuid>9807a144-c36e-470f-8029-0eb1b7f23ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmdAccept</value>
      <webElementGuid>0f8b618e-3463-4355-af59-a361e6899c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Aceptar la información de la ventana</value>
      <webElementGuid>6f653288-5682-4484-a941-3fcf205779d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aceptar la información de la ventana</value>
      <webElementGuid>b4d367ac-2d07-4139-b73c-57b20e89db08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>MouseMoveImage(this, true)</value>
      <webElementGuid>37a8fa3c-ea0b-4aae-85f5-93dfd4167e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>MouseMoveImage(this, false)</value>
      <webElementGuid>3857d818-f81b-49c0-969f-71ea9d80162f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ToolbarHeaderHover</value>
      <webElementGuid>fbf52de0-fc91-4f74-8da6-02ecfb70e8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmdAccept&quot;)</value>
      <webElementGuid>7785cde1-b15d-4f5d-a567-9f3e5359d791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/frame_BODY  PEsta pgina usa marcos, pero su_3d6ef9_1</value>
      <webElementGuid>634493ac-0230-4599-a510-4c523e7ba49e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cmdAccept']</value>
      <webElementGuid>61e19ebe-80f1-49e0-aeed-d9352518a0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Aceptar la información de la ventana']</value>
      <webElementGuid>7c7c2570-2d0d-4f0b-b20c-654881e8a998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>047db7e2-1a80-48b2-a706-2d3f52a51dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnAcceptOn.png' and @name = 'cmdAccept' and @id = 'cmdAccept' and @alt = 'Aceptar la información de la ventana' and @title = 'Aceptar la información de la ventana']</value>
      <webElementGuid>8b9346e6-6c00-4b23-8a00-6a00201e16e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
