<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Razn Social a imprimir_cmdAccept</name>
   <tag></tag>
   <elementGuidId>b2fc1aba-7d60-4f5e-bf11-b8d6287c01bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cmdAccept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cmdAccept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dc5f7bc4-63dd-41dd-b96f-0740c4dbab82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cd01ac54-95c9-4fda-a10d-3ed60cd485a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnAcceptOn.png</value>
      <webElementGuid>01292381-1a91-4052-a04e-e5efe691f007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cmdAccept</value>
      <webElementGuid>7aa3eb03-247f-4a7d-a095-eb89d071836b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmdAccept</value>
      <webElementGuid>188f8eb9-1d4b-44f7-9569-d6b017ab8036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Aceptar la información de la ventana</value>
      <webElementGuid>9d000357-835c-4a3a-b9a3-d7c5930d1f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aceptar la información de la ventana</value>
      <webElementGuid>b6860e0e-f672-4b8e-9521-a597b2faddbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>MouseMoveImage(this, true)</value>
      <webElementGuid>8cba9fa6-9da6-4a29-90fa-f7d4955fbe3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>MouseMoveImage(this, false)</value>
      <webElementGuid>7bdd1003-e3a5-49b9-95f8-55b2eb13a551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ToolbarHeaderHover</value>
      <webElementGuid>3845dd3c-c3aa-4391-9939-c8f06b403735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmdAccept&quot;)</value>
      <webElementGuid>2b6501e1-06c4-4268-9a5f-7c6e94ae94e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/frame_BODY  PEsta pgina usa marcos, pero su_3d6ef9</value>
      <webElementGuid>5fd80d54-ecd4-4f12-bfaf-8f03e43e4940</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cmdAccept']</value>
      <webElementGuid>deb10a56-5a72-46ec-8551-02c908b40883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Aceptar la información de la ventana']</value>
      <webElementGuid>9102861b-6ead-4ea6-9590-df28e2817540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>5c25c3ae-66ee-4f65-b21d-637714b9c279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnAcceptOn.png' and @name = 'cmdAccept' and @id = 'cmdAccept' and @alt = 'Aceptar la información de la ventana' and @title = 'Aceptar la información de la ventana']</value>
      <webElementGuid>32e8afab-81e1-401e-bc99-c6e7297befb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
