<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cdigo del cliente_tctCode (1)</name>
   <tag></tag>
   <elementGuidId>06e10f90-c705-4dc8-8484-d5ec7bd891fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tctCode&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tctCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcbdc6d6-17aa-432b-8cef-5a400cbbc7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>05fb0f00-d127-4538-81c7-679ba3386396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tctCode</value>
      <webElementGuid>8292254a-12a7-4e94-b111-beeacacebb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>85ca89af-a876-414e-a516-dd5f1ad4ca58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>58652d99-0580-4a26-a4fb-aa426842fa02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ac9b2af-fa5c-4d02-b04b-6400bb1fb7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Código del cliente asociado</value>
      <webElementGuid>020d21e2-7142-4616-a88c-f382c9a09809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>tctCode.IsReq=0;tctCode.Alias=&quot;Código del cliente asociado&quot;;tctCode.Maxlength=14;if(ValText(tctCode,&quot;&quot;,&quot;False&quot;)){if (tctCode_Old.value != tctCode.value){ValidateClient(this,&quot;lblCliename&quot;,true,1,&quot;&quot;,0,&quot;&amp;sForm=CA025&amp;sOnChange=InsChangeClient(this)&quot;,false);};}</value>
      <webElementGuid>b6ef2d22-3440-4c27-9d1a-7316a682360b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[2]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>05e735bb-c0be-4992-ab7f-7f9b4885be52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/frame_BODY  PEsta pgina usa marcos, pero su_3d6ef9_1</value>
      <webElementGuid>8cb2a041-67b1-411e-ba1b-1c1b220e3398</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tctCode']</value>
      <webElementGuid>af4501e7-1082-4541-9598-5b1b688e5032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>6248de74-8d5c-4c09-bce4-e9fa24f11949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'tctCode' and @title = 'Código del cliente asociado']</value>
      <webElementGuid>1d3d6902-199f-4afe-beac-f62d6a64a74f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
