<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cdigo del cliente_tctCode</name>
   <tag></tag>
   <elementGuidId>e204069a-6978-4b6e-a74f-83ce13116044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tctCode&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tctCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5d1f51d-d389-4420-a98a-1b9d32a21f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>8ce762f9-926a-47bd-b029-181ae84b8c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tctCode</value>
      <webElementGuid>e4210604-6c0f-48f0-af61-05d80f958f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>229f00b8-6810-463d-a0e4-78cf9938c674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>13c8d4f0-feed-40a8-9483-e87414f59a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>96983b80-8b7d-4ae0-8e9f-3fc53aeae9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Código del cliente asociado</value>
      <webElementGuid>89299cb4-a7ed-41ea-9c29-445c11b5d532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>tctCode.IsReq=0;tctCode.Alias=&quot;Código del cliente asociado&quot;;tctCode.Maxlength=14;if(ValText(tctCode,&quot;&quot;,&quot;False&quot;)){if (tctCode_Old.value != tctCode.value){ValidateClient(this,&quot;lblCliename&quot;,true,1,&quot;&quot;,0,&quot;&amp;sForm=CA025&amp;sOnChange=InsChangeClient(this)&quot;,false);};}</value>
      <webElementGuid>2df2aae8-7544-4226-8dc4-549337116214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[2]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>c857a8e0-c515-416e-b69d-92b618fcbb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/frame_BODY  PEsta pgina usa marcos, pero su_3d6ef9</value>
      <webElementGuid>56c917a7-9b38-4f26-81c5-64e6c53c8e2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tctCode']</value>
      <webElementGuid>734d4708-767d-416b-a945-9fe0b1c227a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>268535ee-9ea2-408e-81fa-482e5d30d633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'tctCode' and @title = 'Código del cliente asociado']</value>
      <webElementGuid>1f1854d9-fcf3-478a-b756-1bcde3624558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
