<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnGuardar</name>
   <tag></tag>
   <elementGuidId>a21e238a-7b5e-4180-8138-17dbe5a10fa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='if(insDisabledButton(document.A392,0)){ ClientRequest(392,2);}; return false']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#A392LI > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4aa9980-8dda-416f-a61b-bb6670d21c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9e4703da-6b54-43a7-b39f-3f7adc79e92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(insDisabledButton(document.A392,0)){ ClientRequest(392,2);}; return false</value>
      <webElementGuid>ec879340-6e96-4a9e-b74e-c23f96bf74f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>insChangeImage(&quot;A392&quot;,1)</value>
      <webElementGuid>feee01dc-d811-46bb-9f6f-f5ffc10e7200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>insChangeImage(&quot;A392&quot;,2)</value>
      <webElementGuid>8bfbea93-3ad5-4c48-9170-8c2fe17cad0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;A392LI&quot;)/a[1]</value>
      <webElementGuid>a0dcc39f-98d3-4352-b8a9-5378be515ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Anexos/frame_BODY            PEsta pgina utiliza frame, pero su BROWSER no lo soportaP        BODY_fraHeader</value>
      <webElementGuid>690d84c9-a459-4854-9ff5-b9c49590b2b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='if(insDisabledButton(document.A392,0)){ ClientRequest(392,2);}; return false']</value>
      <webElementGuid>67bed2a5-ba9c-4f8a-998b-a2131bdd3fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='A392LI']/a</value>
      <webElementGuid>5d7b4a43-675b-41fa-981e-0fbeb9798721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ramo'])[1]/preceding::a[2]</value>
      <webElementGuid>55787d1c-a470-437e-a45f-408e97042665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Robo y riesgos similares'])[1]/preceding::a[2]</value>
      <webElementGuid>c6c9e281-e9eb-4714-ad94-68332be359bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>3140d2f3-b39b-4cf0-9509-a0491c5b7005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[5]/a</value>
      <webElementGuid>61042b19-4779-469c-ba06-c8ff965939aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>bb5013c1-8887-409c-9b6f-dacdda17f17f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
