<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODY            PEsta pgina utiliza frame, pero su BROWSER no lo soportaP        BODY_fraHeader</name>
   <tag></tag>
   <elementGuidId>f29f1daf-c39c-4f2a-bc70-6563768dc330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraHeader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraHeader&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>eedb864f-d004-4578-8dca-8b02cc9c3a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraHeader</value>
      <webElementGuid>ddf05c57-9e3a-4457-987a-f2e3a6dd4580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>744c515f-5f98-40d8-b864-fd5ad2f4a4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>89495895-3ce8-4e35-bc4c-30ba44419d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>e21abd56-9a1e-45f3-9e05-f2944c1e13e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Policy/PolicySeq/CA001_K.aspx?sConfig=InSequence&amp;LoadWithAction=&amp;bMenu=1&amp;sCodispl=CA001</value>
      <webElementGuid>e03645a4-8936-468b-aec8-7e9b848b1f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[2]/frame[1]</value>
      <webElementGuid>d49f5ecd-c221-4d2e-b89a-5f9a4d799136</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraHeader']</value>
      <webElementGuid>2f942a0f-1957-4281-911f-030136915c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset[2]/frame</value>
      <webElementGuid>3aa78fa5-c662-42b7-8d1e-9290f202d54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraHeader' and @src = '../Policy/PolicySeq/CA001_K.aspx?sConfig=InSequence&amp;LoadWithAction=&amp;bMenu=1&amp;sCodispl=CA001']</value>
      <webElementGuid>9a14b549-2e49-487f-baad-8df1f24dacfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
