<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Continuar_cmdAccept</name>
   <tag></tag>
   <elementGuidId>a09e38ea-c71c-4cd9-88ad-bffbffb73af9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cmdAccept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cmdAccept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd6b5d71-855b-4b4f-aa53-0efcf7e630fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2300294-ff3e-4b07-854e-0bc543276627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnAcceptOn.png</value>
      <webElementGuid>8b7552b5-7cfd-4ad8-b759-4d4a551f0fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cmdAccept</value>
      <webElementGuid>b00f5e72-6860-45c7-9953-c000fc72d513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmdAccept</value>
      <webElementGuid>74af7eab-abc5-40f0-88fb-daef0aad644a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Aceptar la información de la ventana</value>
      <webElementGuid>fe54fa72-029b-4c23-a0af-250025665bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aceptar la información de la ventana</value>
      <webElementGuid>077819c1-01aa-479b-b6d9-75fac715c946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>MouseMoveImage(this, true)</value>
      <webElementGuid>2e208778-f51a-4839-8f7d-09a48fc30311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>MouseMoveImage(this, false)</value>
      <webElementGuid>88c457b9-b7a1-4a8c-84b5-581b4bf24abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ToolbarHeaderHover</value>
      <webElementGuid>7e39af12-905c-462f-87e3-394e9d9e1a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmdAccept&quot;)</value>
      <webElementGuid>b24ed3e5-2e27-409a-8df7-50c6bdf5c150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Productores_Intermediarios/frame_BODYOK</value>
      <webElementGuid>5bdbd91e-6ca8-412e-ae58-28d8e280b0af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cmdAccept']</value>
      <webElementGuid>d4d5ef2d-3170-42a0-b6f2-7cb5a624bcf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CA024']/div[2]/div[4]/a/img</value>
      <webElementGuid>885c09cf-4abe-4330-ba52-1341524bdc99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Aceptar la información de la ventana']</value>
      <webElementGuid>ffbfa1ca-2fa7-450b-a7bb-b45c3b305dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>aa908199-0f97-412b-b9b6-4c3a77e5769f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnAcceptOn.png' and @name = 'cmdAccept' and @id = 'cmdAccept' and @alt = 'Aceptar la información de la ventana' and @title = 'Aceptar la información de la ventana']</value>
      <webElementGuid>2a122d7a-29d1-4112-943e-3e81751374b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
