<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODYOK</name>
   <tag></tag>
   <elementGuidId>e27938b5-0ab8-4085-8899-f52b68b1f3ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>388296cc-b0d5-4fb6-8e40-37125cc03525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>framespacing</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9fd69237-2166-4b41-b92e-d46097f3f66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>e4fa5f0e-95f8-4fa4-80b8-4dd2bdf268a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>bd31ae66-7e5d-40fb-85e3-a28c1371f9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c597b5a0-1936-4d5a-a553-65170f15df5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraGeneric</value>
      <webElementGuid>56e66644-9f19-465d-b541-e56cb4f01864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>GridPopUp.aspx?Type=PopUp&amp;Action=Add&amp;Index=-1&amp;nMainAction=304&amp;sCodispl=CA024&amp;nCommityp=1&amp;nPercent=0,00&amp;sInd_Comm=1&amp;sConColl=2&amp;nCommplan=-32768</value>
      <webElementGuid>23ad7b80-034d-464f-8a10-8f2d1d893cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>f7e13734-d36e-4c13-adc0-bb11f487b09c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>64ed3db7-6397-4f19-8cc3-647e5cd5cc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>8facbf5e-6970-4756-ad49-5af3ac653932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'GridPopUp.aspx?Type=PopUp&amp;Action=Add&amp;Index=-1&amp;nMainAction=304&amp;sCodispl=CA024&amp;nCommityp=1&amp;nPercent=0,00&amp;sInd_Comm=1&amp;sConColl=2&amp;nCommplan=-32768']</value>
      <webElementGuid>055560c7-8171-48df-9082-ce2706e564b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
