<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODY</name>
   <tag></tag>
   <elementGuidId>646f45c0-6814-4287-a3d4-5d772d93c1fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>df267e8c-5237-4f32-9d94-4cac9ee936fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>framespacing</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>10675621-cf54-4e2a-a340-01773f53c194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>e7023052-e9f8-48c2-af58-996781ab7779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>49a35145-99ef-4d47-b3ef-f697be094159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b7355723-1c1c-437f-9a4b-fa5189ad502c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraGeneric</value>
      <webElementGuid>80cfe443-d119-4bce-b484-b51877c37de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>GridPopUp.aspx?Type=PopUp&amp;Action=Add&amp;Index=-1&amp;nMainAction=304&amp;sCodispl=CA024&amp;nCommityp=1&amp;nPercent=0,00&amp;sInd_Comm=1&amp;sConColl=2&amp;nCommplan=-32768</value>
      <webElementGuid>f653ee01-766f-43a3-ba76-069802d573ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>407e4235-710e-4c06-badb-0aabd535e6f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>d22a8259-64f2-4743-b05b-514f24408e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>026297d2-3272-4b6a-a9d4-d61c75fbb867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'GridPopUp.aspx?Type=PopUp&amp;Action=Add&amp;Index=-1&amp;nMainAction=304&amp;sCodispl=CA024&amp;nCommityp=1&amp;nPercent=0,00&amp;sInd_Comm=1&amp;sConColl=2&amp;nCommplan=-32768']</value>
      <webElementGuid>a70f8f97-23b4-4536-87ee-4b0f9216a50a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
