<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PorcentajeDeParticipacin</name>
   <tag></tag>
   <elementGuidId>bb0d7b2c-ce41-4d43-b1ec-1a7f36e1f2e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tcnShare&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tcnShare']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2c68407-a8bc-43a1-aebb-48a1c3edb018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>b29f8f19-d3c7-4470-a98c-c0b904fe6efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tcnShare</value>
      <webElementGuid>65f18f0e-5a6a-4201-a1a9-3e63b6f1320c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2736a435-6704-4cac-aeda-1133722999f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>8d4842f0-963f-4115-a771-ace16002b6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2778591d-68fa-42b9-84e7-afe2a0cb7863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Porcentaje con el que participa el intermediario sobre la comisión de la póliza</value>
      <webElementGuid>39df7ff9-0922-4af6-a8fb-e2c40cfe2a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>self.document.forms[0].tcnShare.HolePlace='03'; self.document.forms[0].tcnShare.IsReq=0; self.document.forms[0].tcnShare.ShowThousand=0; self.document.forms[0].tcnShare.Alias='Porcentaje con el que participa el intermediario sobre la comisión de la póliza'; self.document.forms[0].tcnShare.DecimalPlace=02;if(ValNumber(this,'.',',','false',2)){}</value>
      <webElementGuid>fc7db092-637c-4c17-a3dc-12389b6a4e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CA024&quot;)/table[1]/tbody[1]/tr[8]/td[2]/input[1]</value>
      <webElementGuid>e82d68bc-d500-45f1-a5a7-7c93c9272fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Productores_Intermediarios/frame_BODY  PEsta pgina usa marcos, pero su explorador no los admite.P  BODY_fraFolder</value>
      <webElementGuid>49810d2b-5722-4a8d-9ddb-174fe5934e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tcnShare']</value>
      <webElementGuid>56babf04-04d8-4c97-a104-3dc9c63320e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CA024']/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>5d1bd04a-8b76-49f2-8df8-e52d9f467ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/input</value>
      <webElementGuid>c5ac99ba-d782-435c-ada9-3367e1326c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'tcnShare' and @title = 'Porcentaje con el que participa el intermediario sobre la comisión de la póliza']</value>
      <webElementGuid>f8cfdf10-3f19-4ed4-924f-f05ea5d16779</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
