<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cdigo_valIntermed</name>
   <tag></tag>
   <elementGuidId>4b18e6eb-81eb-45b9-b397-30ca74ef88e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;valIntermed&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='valIntermed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51a9e4ca-f713-4fc8-9376-5bbb0d69bbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>f577fc19-262f-4d51-8090-087afc5f7670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>valIntermed</value>
      <webElementGuid>3b9f794c-cb95-40aa-8fa5-672be21965ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>50b0a4aa-c51a-4fec-b87f-49745e600b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>66a7f754-e8e4-4e32-9983-43c8fb90cf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1b711eb3-205d-4675-9ade-4250e972f3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Código del intermediario entre el tomador y la compañía</value>
      <webElementGuid>408a2d2c-e77b-4f1c-96e3-a6ca38339feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>self.document.forms[0].valIntermed.HolePlace='010'; self.document.forms[0].valIntermed.IsReq=0; self.document.forms[0].valIntermed.ShowThousand=0; self.document.forms[0].valIntermed.Alias='Código del intermediario entre el tomador y la compañía'; self.document.forms[0].valIntermed.DecimalPlace=00;if(ValNumber(this,'.',',','false',0)){ShowValues(this,true,true,false);ShowChangeValues('304','1');}</value>
      <webElementGuid>6957457c-cecd-45b6-b841-bcdac371df4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CA024&quot;)/table[1]/tbody[1]/tr[3]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>bc42a9d9-a2bf-42c3-be80-fa35272a4d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Productores_Intermediarios/frame_BODY</value>
      <webElementGuid>c91ee60c-a809-4d74-8218-b3acea520a1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='valIntermed']</value>
      <webElementGuid>f458a9a4-26ef-4d25-a3f7-fdeebf111ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CA024']/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>e5db136d-960b-4136-9fc6-b28a278762e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>c1cb5d62-9838-4bf0-801c-e4a331deb037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'valIntermed' and @title = 'Código del intermediario entre el tomador y la compañía']</value>
      <webElementGuid>5b7c5524-3069-4899-ac6b-6d606884a57c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
