<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Intermediario</name>
   <tag></tag>
   <elementGuidId>1257d76b-c498-4f54-9a58-ffd5ab0a3c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='CA024']/table/tbody/tr/td/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a59c95a1-a65a-4dce-b196-f66c852b9b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intermediario</value>
      <webElementGuid>a687d0ca-f96a-4389-8722-dee5baed7a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CA024&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;HighLighted&quot;]/label[1]</value>
      <webElementGuid>9b3f13a8-4e1e-4d0c-9cd1-29d5e193f8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Productores_Intermediarios/frame_BODYFraFolder</value>
      <webElementGuid>f30f5a9e-7bc9-4cb9-8a38-f6cf6b0e9ede</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CA024']/table/tbody/tr/td/label</value>
      <webElementGuid>70b200ed-af93-45ea-8c0b-bf7ba4dc843c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intermediarios'])[1]/following::label[1]</value>
      <webElementGuid>6aa8a257-09bd-4bdd-ac99-082f7ca4dc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código'])[1]/preceding::label[1]</value>
      <webElementGuid>c5d94d64-75b5-4a20-87ed-a71b37e285ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALLE FERTIL SA'])[1]/preceding::label[2]</value>
      <webElementGuid>64c5c530-8a04-4e4b-b316-8984e57a0b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intermediario']/parent::*</value>
      <webElementGuid>926ac942-158c-42c3-8324-64a8563e7d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>9ff72541-eb8a-480d-bd0d-2f6459206bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Intermediario' or . = 'Intermediario')]</value>
      <webElementGuid>6bedd04f-0746-4ef5-8880-b805617d4689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
