<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Producto_btnvalProduct</name>
   <tag></tag>
   <elementGuidId>9d2cf52e-c7ee-4879-bde2-3f1b0247a187</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnvalProduct</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a6cf4327-d572-44ba-ae89-b5de36646d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>18a3edc8-4efc-4013-ae3e-6ce6218abee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/images/btn_ValuesOn.png</value>
      <webElementGuid>d4ddcebe-f694-4501-9c19-9e6ea473a17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnvalProduct</value>
      <webElementGuid>c48bddbb-8f4e-4390-818f-3d26400a5993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnvalProduct</value>
      <webElementGuid>0c415fe7-43d6-4e7a-9ce7-f9acecfa85f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Productos del ramo (Valores posibles)</value>
      <webElementGuid>39b34536-c60c-4a7e-96dd-3977c63077aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Productos del ramo (Valores posibles)</value>
      <webElementGuid>afbc8f47-4be1-4c3a-9260-534d09971719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>MouseMoveImage(this, true)</value>
      <webElementGuid>620652ad-c1ff-469a-a483-ae318b298f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>MouseMoveImage(this, false)</value>
      <webElementGuid>03d8e3f9-4a94-4c8f-a044-068ddc9fee49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnvalProduct&quot;)</value>
      <webElementGuid>c44c01e2-3169-4303-9c8f-a379330590c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)/frame_BODY            PEsta pgina utiliza f_69e94c</value>
      <webElementGuid>6003fa83-7e64-4cd6-bf00-f51f7a847a4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='btnvalProduct']</value>
      <webElementGuid>5dd25a40-31f5-4731-8f91-892dcabaa8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Productos del ramo (Valores posibles)']</value>
      <webElementGuid>29558a23-3230-4cfb-a429-c5e0ada9f661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/a/img</value>
      <webElementGuid>4982a9df-a32f-40ca-aa51-6af94226ce3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/images/btn_ValuesOn.png' and @name = 'btnvalProduct' and @id = 'btnvalProduct' and @alt = 'Productos del ramo (Valores posibles)' and @title = 'Productos del ramo (Valores posibles)']</value>
      <webElementGuid>280a5fec-724d-43b0-aada-7b48af5da87e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
