<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oficina_cbeOfficeAgen</name>
   <tag></tag>
   <elementGuidId>b87c535a-e5aa-429d-86ed-566326e638c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cbeOfficeAgen&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cbeOfficeAgen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14eef2b4-3926-4ab8-b49e-4be283493a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>7157f7c3-c00a-4f6f-ab2f-1bfdcceb12be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbeOfficeAgen</value>
      <webElementGuid>7b1940ef-33bd-47e4-bb64-a2e43a43398f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b3aa913b-f5dc-4409-8313-662865fcc44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5f5f408d-44e8-4eb6-91d1-60683441895d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>36fd8fc5-29a2-46c6-a8fc-2246db48345f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Oficina a la que pertenece la póliza en tratamiento</value>
      <webElementGuid>73caecbb-4a8d-4af8-b4e2-180bef0fdb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>self.document.forms[0].cbeOfficeAgen.HolePlace='05'; self.document.forms[0].cbeOfficeAgen.IsReq=0; self.document.forms[0].cbeOfficeAgen.ShowThousand=0; self.document.forms[0].cbeOfficeAgen.Alias='Oficina a la que pertenece la póliza en tratamiento'; self.document.forms[0].cbeOfficeAgen.DecimalPlace=00;if(ValNumber(this,'.',',','false',0)){ShowValues(this,true,true,false);insInitialAgency(2);}</value>
      <webElementGuid>67c88c84-d819-464f-8942-f166fd08734c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divOfficeA2&quot;)/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>27244507-2cdb-42d2-8591-c7671d29877c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)/frame_BODY            PEsta pgina utiliza f_69e94c</value>
      <webElementGuid>7f1e5c8f-77ac-45de-96d4-8715011f1ea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cbeOfficeAgen']</value>
      <webElementGuid>22696225-854c-4f41-b7c1-318de04c2211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divOfficeA2']/table/tbody/tr/td/input</value>
      <webElementGuid>ef8e6033-85a1-489d-9bb7-c85b9eb01db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>db247974-604b-4f9d-b8aa-227aab665270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'cbeOfficeAgen' and @title = 'Oficina a la que pertenece la póliza en tratamiento']</value>
      <webElementGuid>8fd2908b-5df2-4da9-8ee5-a13ef40a7e82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
