<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agencia_cbeAgency</name>
   <tag></tag>
   <elementGuidId>197ff6ad-ba7b-47c2-91ef-9133ff6b0db1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cbeAgency&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cbeAgency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f26d5d5b-a8ac-481d-9c2a-888a3feace28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>79a305aa-8113-45bd-9190-84474c1f6931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbeAgency</value>
      <webElementGuid>503d60ce-a54b-490e-bbfb-0761bf463dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>51da92ba-ccdf-4cbe-a02e-40cfe3e6a1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d9d72354-7acc-4882-9f82-76408ca1a68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>07968f13-50ec-454c-9223-663d8c65888d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Agencia a la que pertenece la póliza en tratamiento</value>
      <webElementGuid>4df4a648-8977-48b5-9ef5-bcfcdbd74ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>self.document.forms[0].cbeAgency.HolePlace='05'; self.document.forms[0].cbeAgency.IsReq=0; self.document.forms[0].cbeAgency.ShowThousand=0; self.document.forms[0].cbeAgency.Alias='Agencia a la que pertenece la póliza en tratamiento'; self.document.forms[0].cbeAgency.DecimalPlace=00;if(ValNumber(this,'.',',','false',0)){ShowValues(this,true,true,false);insInitialAgency(3);}</value>
      <webElementGuid>0c4517cd-7998-47f6-8820-dcfeab7e88a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divAgency2&quot;)/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>0d148975-0586-48fb-87de-b07b6e44959d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Frames/frame_FraHeader</value>
      <webElementGuid>b0697266-9f5b-42d4-bb20-aefd02b0855d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cbeAgency']</value>
      <webElementGuid>c6420527-f688-4514-a5eb-b3f11943c5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAgency2']/table/tbody/tr/td/input</value>
      <webElementGuid>05822124-6d0b-4ba2-9480-f3fdd8377a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/div/table/tbody/tr/td/input</value>
      <webElementGuid>f10ca2ce-f4ec-46fa-86c5-52ffb9301531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'cbeAgency' and @title = 'Agencia a la que pertenece la póliza en tratamiento']</value>
      <webElementGuid>db4f8838-7f73-4f68-adfb-fd3fee53a38d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
