<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CasaCentral</name>
   <tag></tag>
   <elementGuidId>bc5d37da-4fee-437a-9419-01c2e8404f5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;cbeOffice&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='cbeOffice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b9f2cb15-8f1e-4fb1-97c5-b7e3b6e2852d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fc819724-873d-4095-9752-63d22937be3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbeOffice</value>
      <webElementGuid>1d030377-7b91-43cb-8aa2-142447779096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f6550f65-4db8-4987-abf2-32570eff429d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sucursal a la que pertenece la póliza</value>
      <webElementGuid>41ed67a5-bca8-4b57-9011-0e6d5dd094ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>BlankOfficeDepend();insInitialAgency(1)</value>
      <webElementGuid>e4099439-dec6-4322-aa1c-a6da71f8d7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Casa Central</value>
      <webElementGuid>cf166ca2-f392-4904-ae31-09e74da82692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divOffice2&quot;)/select[1]</value>
      <webElementGuid>1feb6360-7b2b-4a12-bc53-60b556e5bb0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)/frame_BODY            PEsta pgina utiliza f_69e94c</value>
      <webElementGuid>da6b7029-26b9-400d-98dc-d6cc85162705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='cbeOffice']</value>
      <webElementGuid>0856ca7b-a394-4fdd-8944-7247f3aee530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divOffice2']/select</value>
      <webElementGuid>c3c6c2d9-e564-4422-ac7d-9bdaae4fd1d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sucursal'])[1]/following::select[1]</value>
      <webElementGuid>6e907cd1-412c-4da2-b774-7a00ab8d2d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de vigencia'])[1]/following::select[1]</value>
      <webElementGuid>9ea80d54-17a7-49c1-a6db-c60b48ed3c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oficina'])[1]/preceding::select[1]</value>
      <webElementGuid>41778c48-3897-4396-a7f0-328e15efff2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agencia'])[1]/preceding::select[1]</value>
      <webElementGuid>07a992bb-5845-4231-9667-e513a74946f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>5a2a0dcc-fe46-4c2d-bc67-1de02bd58a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cbeOffice' and @title = 'Sucursal a la que pertenece la póliza' and (text() = 'Casa Central' or . = 'Casa Central')]</value>
      <webElementGuid>25cbed98-ee13-49f8-88de-a9eeac7361af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
