<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ComboRamo</name>
   <tag></tag>
   <elementGuidId>b9a9ea99-9882-4fd2-a29e-17d7a6a34532</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;cbeBranch&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='cbeBranch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>847ae02b-7a06-429f-91bc-6a20d3523493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2af8192c-f5c9-4c25-ab1d-02ccaf01d4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbeBranch</value>
      <webElementGuid>0e19ba6a-872a-4d94-947e-9ee57113cbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3394c74c-e9a0-4576-8273-f0133297d7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ramos de Seguros</value>
      <webElementGuid>da1a19be-8eb8-4bf0-b208-61b72bc67d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>InsChangecbeBranch(this.value);ShowChangeValues(&quot;nBranch&quot;)</value>
      <webElementGuid>bad79439-f87b-486c-b5f3-ac34c0765454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comb. Familiar e IntegralesRobo y riesgos similaresVida colectivoRiesgos variosAccidentes PersonalesVida ObligatorioVida IndividualSaludSepelioGanado</value>
      <webElementGuid>ed4024e5-3492-49df-a77e-464f6ff867f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[9]/td[2]/select[1]</value>
      <webElementGuid>b087bc28-dc46-460d-ad68-ae919dfd7bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Frames/frame_FraHeader</value>
      <webElementGuid>259cdf00-8186-4b86-b5c6-a77d75005a06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='cbeBranch']</value>
      <webElementGuid>0ad6bacf-246e-4422-b607-5dc285ed2204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ramo'])[1]/following::select[1]</value>
      <webElementGuid>51127f4e-b594-49ba-ab06-63f32579fccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canal de venta'])[1]/following::select[2]</value>
      <webElementGuid>aeb1e553-d05a-4d26-8741-b77300f3c5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producto'])[1]/preceding::select[1]</value>
      <webElementGuid>600dc8e8-f2d6-46ab-ba08-945b6047d179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Póliza'])[1]/preceding::select[1]</value>
      <webElementGuid>261be602-399b-40d7-a047-93de0060517d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/select</value>
      <webElementGuid>4ec7d7df-35c2-4f86-a1af-934bdf3fedb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cbeBranch' and @title = 'Ramos de Seguros' and (text() = 'Comb. Familiar e IntegralesRobo y riesgos similaresVida colectivoRiesgos variosAccidentes PersonalesVida ObligatorioVida IndividualSaludSepelioGanado' or . = 'Comb. Familiar e IntegralesRobo y riesgos similaresVida colectivoRiesgos variosAccidentes PersonalesVida ObligatorioVida IndividualSaludSepelioGanado')]</value>
      <webElementGuid>eee91b5a-b30c-4c48-a5a0-b8454b92caff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
