<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODY</name>
   <tag></tag>
   <elementGuidId>1775f234-9771-4ce2-b4f5-6ebf30e12b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>a1f09daf-9b44-409c-accb-d574c5eb61ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>f4de71ad-0c83-47a7-a384-0a0865b8998f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Blank.aspx</value>
      <webElementGuid>f3f1643a-3e5f-406b-aca3-530b05615d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[2]/frame[2]</value>
      <webElementGuid>37779201-9267-4a93-9d58-5e2082342a8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>4b644c8a-a94e-4448-8c52-5a373cf929f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset[2]/frame[2]</value>
      <webElementGuid>9e7976fd-d73b-4066-a319-0c3768ce64ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'Blank.aspx']</value>
      <webElementGuid>40cefb88-a1ee-4e00-b994-29a38bc81dbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
