<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Noaplica_Sel (1) - Copy</name>
   <tag></tag>
   <elementGuidId>b62e207d-adb7-4e75-ae0e-4bed111dfdb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Sel'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>024e8907-df48-4824-ba6d-3951ff9db92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>CHECKBOX</value>
      <webElementGuid>c537eeb7-b7b9-448d-8e77-e005e8d28a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Sel</value>
      <webElementGuid>9965aff2-4961-4d9a-b091-ce8fa50a9aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sel</value>
      <webElementGuid>a91409fc-7bfc-41ad-896c-8cbb22e790e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6fedacd3-39e4-4154-97fc-f7f6c21a8275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>85e27aed-ed78-4447-b81b-c8f8c605db8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>marrArray[this.value].Sel=this.checked;insCheckSelClick(this,4);</value>
      <webElementGuid>e9f08459-e528-49ac-bcd8-958e9cd295a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[@class=&quot;grddata&quot;]/tbody[1]/tr[@id=&quot;gridmarrArray&quot;]/td[1]/input[@id=&quot;Sel&quot;]</value>
      <webElementGuid>0bf6fb28-c437-460b-8da5-ea5551b393dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Coberturas/frame_BODYPEsta pgina</value>
      <webElementGuid>e03f0a9d-03eb-4c63-bf8c-c3a6d6c33c37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Sel'])[5]</value>
      <webElementGuid>bf52746e-85c0-4a3b-b5ab-0d4829ffed56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='gridmarrArray']/td/input)[309]</value>
      <webElementGuid>ce79e433-5ba3-47f5-b791-6f75be310d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/input</value>
      <webElementGuid>e10c13a8-2120-4d9f-a517-bdc4922434cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'CHECKBOX' and @id = 'Sel' and @name = 'Sel']</value>
      <webElementGuid>f07276b7-00ac-4b8b-967e-e45d7d45e24c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
