<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Noaplica_Sel</name>
   <tag></tag>
   <elementGuidId>2c5b09d9-b9aa-49d6-a48c-7284de02cc21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Sel'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1422d55-4611-4c21-8dcb-58f7dd8f97dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>CHECKBOX</value>
      <webElementGuid>edfa2d0f-04ef-4bcd-a096-936a7d7facd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Sel</value>
      <webElementGuid>1cc473b3-3c4f-4adf-a41a-d6e331a55c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sel</value>
      <webElementGuid>9e9f3653-070e-44e8-8093-49d294aef3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>362d4bda-3fd3-4ba7-b605-a90fbac9b060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>adea88f9-7140-4555-a6bf-04a080a215cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>marrArray[this.value].Sel=this.checked;insCheckSelClick(this,3);</value>
      <webElementGuid>af26839b-646a-489e-bb60-ac4f5f3ed040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[@class=&quot;grddata&quot;]/tbody[1]/tr[@id=&quot;gridmarrArray&quot;]/td[1]/input[@id=&quot;Sel&quot;]</value>
      <webElementGuid>e32d554e-8d1e-40ce-8a86-3b59c7cba7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Coberturas/frame_BODY</value>
      <webElementGuid>9575f28b-b218-4c24-a584-47b1b8219e19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Sel'])[4]</value>
      <webElementGuid>7bf5a2c5-8a85-4401-82e5-20bf48af36a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='gridmarrArray']/td/input)[232]</value>
      <webElementGuid>562b8d4c-4b95-4aa6-b86c-322d7d5ce78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>f37e3cf5-a868-447b-8b14-d1e937664857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'CHECKBOX' and @id = 'Sel' and @name = 'Sel']</value>
      <webElementGuid>5f801269-f9b2-448a-abe8-042cc3605e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
