<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Iniciar</name>
   <tag></tag>
   <elementGuidId>b7a92e29-17f4-483b-abfb-d694b279c81f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginButton_CD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='LoginButton_CD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>23b162fe-311a-4682-a291-15f56d1997bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginButton_CD</value>
      <webElementGuid>593d6070-e920-495d-868f-e57a6e429640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxb</value>
      <webElementGuid>bd30ed0e-1fa6-414b-bd1e-7ce3be817285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			Iniciar
		</value>
      <webElementGuid>6eb540ae-d368-4768-a7cd-6b018a793bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginButton_CD&quot;)</value>
      <webElementGuid>f2b8c409-6d2c-48b5-b9da-a2e12aeca7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_VisualTIME 7.0/iframe_Iniciar sesin_ctl00_LogInPopupControl_CIF-1</value>
      <webElementGuid>9b122a7f-66d9-4699-8e54-ed129c0ac4a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='LoginButton_CD']</value>
      <webElementGuid>18833724-e802-467c-a451-18db81ba87d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='LoginButton_B']/div[2]</value>
      <webElementGuid>8255c208-a796-4128-867b-e3fb1993adbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando…'])[1]/following::div[3]</value>
      <webElementGuid>b201ae44-293f-4934-a565-bc1586f5af28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valor inválido'])[3]/following::div[3]</value>
      <webElementGuid>27cc651a-b36e-452f-adfb-2273b770bd3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::div[2]</value>
      <webElementGuid>ccdf56c3-952c-48ab-b70f-026f75f49fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div[2]</value>
      <webElementGuid>a515cffe-5907-4fe0-84fa-d6e62b42eb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'LoginButton_CD' and (text() = '
			Iniciar
		' or . = '
			Iniciar
		')]</value>
      <webElementGuid>199eb0a4-705f-42de-acc3-2827dae94beb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
