<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Iniciar sesin_ctl00_LogInPopupControl_CIF-1</name>
   <tag></tag>
   <elementGuidId>8de18dba-9f9a-416c-95b1-c086260b2289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_LogInPopupControl_CIF-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ctl00_LogInPopupControl_CIF-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ab45903b-1d72-4fdd-b3ac-3f82a4284e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_LogInPopupControl_CIF-1</value>
      <webElementGuid>9dd7cf62-bdee-4dfe-87c9-ebfafe34b00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Authentication/UserLogIn.aspx</value>
      <webElementGuid>fb08c8e9-d7ff-4f20-acd4-996c0db23633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>fa3ab34a-1e14-4b4c-a15a-b103eaf84e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2a8b706f-bc83-4a50-9f0c-fd73d10fedc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_LogInPopupControl_CIF-1&quot;)</value>
      <webElementGuid>8f70f4c1-31b3-4e4c-a64e-e712619fb18f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ctl00_LogInPopupControl_CIF-1']</value>
      <webElementGuid>1e3ca0c4-ba49-4da0-becd-20593173c0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_LogInPopupControl_CIFD-1']/iframe</value>
      <webElementGuid>304cc098-a625-4aa2-972e-4daa8dc9786a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar sesión'])[1]/following::iframe[1]</value>
      <webElementGuid>494bdd8d-f029-4322-839d-546630313e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando…'])[2]/following::iframe[1]</value>
      <webElementGuid>f31a7090-a804-4575-9d9d-4840717ec3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Ha olvidado su contraseña?'])[1]/preceding::iframe[1]</value>
      <webElementGuid>b4a29dc3-f00d-4a91-b3e3-d37d370a96a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registro'])[1]/preceding::iframe[1]</value>
      <webElementGuid>74c60e3b-38e9-4f29-89fc-858e4a8645f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b55cac28-eaa4-471d-8548-8ac3150c8b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ctl00_LogInPopupControl_CIF-1' and @src = '/Authentication/UserLogIn.aspx']</value>
      <webElementGuid>b881afb5-033b-482f-9eaf-a5564ef3ffa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
