<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre usuario_EmailAddressTextBox</name>
   <tag></tag>
   <elementGuidId>b9847b6c-e233-4b8b-b6fe-fa10a8205419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmailAddressTextBox_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmailAddressTextBox_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07e1a99d-73fd-4eb1-ae3e-95f70199f0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Silver dxeEditAreaSys dxh0</value>
      <webElementGuid>9d196dfd-e07b-4289-a9c7-13730fd19e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailAddressTextBox</value>
      <webElementGuid>d1784142-8768-4448-9a08-6ba42b0e8878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('EmailAddressTextBox', event)</value>
      <webElementGuid>10db4172-a32d-44a1-8cf3-7abffc214d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailAddressTextBox_I</value>
      <webElementGuid>9dbe4189-acc6-43d4-acd6-3f3a458825e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxEValueChanged('EmailAddressTextBox')</value>
      <webElementGuid>9715411e-e672-4b7a-a4a3-dfebc5eed0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('EmailAddressTextBox')</value>
      <webElementGuid>bec4a45d-1a6c-4699-9423-95620d039b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('EmailAddressTextBox')</value>
      <webElementGuid>4738a4ac-3d23-486b-b1d9-993e16eb0b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40309e77-9faf-4c91-b080-9895ed7d09d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>aspxEKeyDown('EmailAddressTextBox', event)</value>
      <webElementGuid>94aa46bb-8efb-4830-982d-00a4c0e34fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailAddressTextBox_I&quot;)</value>
      <webElementGuid>ffb67dbb-a104-4735-b834-aee19e7189a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_VisualTIME 7.0/iframe_Iniciar sesin_ctl00_LogInPopupControl_CIF-1</value>
      <webElementGuid>94cf1cf0-223c-496c-8c06-5998e5dd576f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmailAddressTextBox_I']</value>
      <webElementGuid>405dc55e-b6e8-4efd-9d5e-2c9875ba1114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='EmailAddressTextBox']/tbody/tr/td/input</value>
      <webElementGuid>27bb2bcb-c2ad-4679-b330-685902c3ebbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>2d4067c9-2ee6-4429-a782-ad949e0c8169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'EmailAddressTextBox' and @id = 'EmailAddressTextBox_I' and @type = 'text']</value>
      <webElementGuid>d89509d3-378f-4304-b334-814803b39530</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
