<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingles_txtSearchTransacction</name>
   <tag></tag>
   <elementGuidId>ebc982f8-5622-4639-9adf-4c9f982e883b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSearchTransacction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSearchTransacction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00447e79-bf41-4701-8c73-b54bdc6e9123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSearchTransacction</value>
      <webElementGuid>659cbaf2-df81-484e-83eb-db9227861018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cadb456-d75a-44d9-aea9-e54874681d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>b8f150d3-64c4-4c37-b0b0-07158cabc4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>71</value>
      <webElementGuid>da05a525-9edb-4c96-896f-eedab1e9e447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>45405045-dfaa-49c9-8c39-bbc361465f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f007407c-f368-47d4-b956-c2b8a8e6cd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSearchTransacction&quot;)</value>
      <webElementGuid>4ce2936f-0b5d-4eb8-9659-421a50efe4f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSearchTransacction']</value>
      <webElementGuid>20bf2afa-c1ff-4bf1-9f13-09bc57fc2752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header_message']/div/input[5]</value>
      <webElementGuid>a291db9e-8750-454b-bb0d-e0dc49912e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[5]</value>
      <webElementGuid>8f6d41ef-1c18-4b28-84a6-8aae83d7bc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtSearchTransacction' and @type = 'text']</value>
      <webElementGuid>c3447763-5178-4994-bdaf-18b4ff51db8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
