<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrasea_PasswordTextBox</name>
   <tag></tag>
   <elementGuidId>f42aa19c-b72c-415f-aa85-33a033ac05eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PasswordTextBox_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PasswordTextBox_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da6d8fda-96b8-401d-9951-3b0d45e390a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Silver dxeEditAreaSys  dxh0</value>
      <webElementGuid>a7d52a6a-af97-4ce5-b5f3-24f2c76da5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PasswordTextBox</value>
      <webElementGuid>e7889d21-7d8d-451a-aec7-78c2b3abf16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>aspxEKeyUp('PasswordTextBox', event)</value>
      <webElementGuid>54117686-1fa6-4615-8685-b8f693e558b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PasswordTextBox_I</value>
      <webElementGuid>fdac1d9d-f7f1-418b-af48-281bf2b7c47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxEValueChanged('PasswordTextBox')</value>
      <webElementGuid>a15daa9d-2ed8-40bf-8f7a-afc804e6013d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('PasswordTextBox')</value>
      <webElementGuid>df846fab-5b01-4315-b19b-84020f871029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('PasswordTextBox')</value>
      <webElementGuid>07575fde-6554-4fad-9040-26ba0033fa71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c23324aa-7528-4449-a132-dca12bb9e97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>aspxEKeyDown('PasswordTextBox', event)</value>
      <webElementGuid>cf7ada46-e5b0-4ae2-979b-1c2e4078f72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasswordTextBox_I&quot;)</value>
      <webElementGuid>d142a9ab-45e2-46c9-8fa7-d3ebdec6a7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_VisualTIME 7.0/iframe_Iniciar sesin_ctl00_LogInPopupControl_CIF-1</value>
      <webElementGuid>5178823c-98b0-4388-929f-4e56bb9bc08f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PasswordTextBox_I']</value>
      <webElementGuid>2f9fc349-cc52-4bfe-ad8f-8b4a3303eed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='PasswordTextBox']/tbody/tr/td/input</value>
      <webElementGuid>f90e4ec9-bfa9-4f57-ada9-fe6afdedf667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>84ad8957-5667-433f-adbf-00439ae292c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'PasswordTextBox' and @id = 'PasswordTextBox_I' and @type = 'password']</value>
      <webElementGuid>27b011c8-5061-4bc4-89af-1d6599c29548</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
