<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contratante</name>
   <tag></tag>
   <elementGuidId>62680200-fa4b-4f52-a15b-d8585b72a32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.FIELD > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='gridmarrArray']/td[3]/label/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e6799658-225d-467a-a8a0-879f0c4193d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>JAVASCRIPT:EditRecord(0,nMainAction,'Update','nRole=1&amp;sClient=&amp;nCoverPos=-32768&amp;sSmoking=&amp;sCodisp=CA025&amp;sWindowDescript=Asegurables&amp;nWindowTy=9')</value>
      <webElementGuid>6fcdb534-8d23-47d6-acc8-0879caa443ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contratante</value>
      <webElementGuid>1afc2ec6-92e5-49d1-9b36-6adda2fd1fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[@class=&quot;grddata&quot;]/tbody[1]/tr[@id=&quot;gridmarrArray&quot;]/td[3]/label[@class=&quot;FIELD&quot;]/a[1]</value>
      <webElementGuid>37be4de8-d2b5-45b5-899f-b76f4205a222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  A_4bf224/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>9eb3ec51-d565-4477-86fb-06ed9e5b54f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='gridmarrArray']/td[3]/label/a</value>
      <webElementGuid>465c979f-4da1-4962-8386-8e6e7d86b5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Contratante')]</value>
      <webElementGuid>ffc3fb3f-853c-455e-8e9f-c872ff46fbd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Razón Social a imprimir'])[1]/following::a[2]</value>
      <webElementGuid>a2a1d6aa-e66d-4090-acfa-2051007262f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre a imprimir'])[1]/following::a[2]</value>
      <webElementGuid>493780b6-e33f-41f7-96cf-480dc2f88256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asegurado'])[1]/preceding::a[2]</value>
      <webElementGuid>e64ccfdf-77bf-4919-87c1-09c45989d2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intermediario'])[1]/preceding::a[4]</value>
      <webElementGuid>fc4c7a54-2702-4e93-9506-e26b6acf699f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contratante']/parent::*</value>
      <webElementGuid>56a29269-d5c3-44fc-8af7-83442052bc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;JAVASCRIPT:EditRecord(0,nMainAction,'Update','nRole=1&amp;sClient=&amp;nCoverPos=-32768&amp;sSmoking=&amp;sCodisp=CA025&amp;sWindowDescript=Asegurables&amp;nWindowTy=9')&quot;)]</value>
      <webElementGuid>3234f730-3cd7-402c-b3e7-5eb11953ab8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/a</value>
      <webElementGuid>ac0fd3eb-2019-4d3b-9f72-dcfa3d97dd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;JAVASCRIPT:EditRecord(0,nMainAction,&quot; , &quot;'&quot; , &quot;Update&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;nRole=1&amp;sClient=&amp;nCoverPos=-32768&amp;sSmoking=&amp;sCodisp=CA025&amp;sWindowDescript=Asegurables&amp;nWindowTy=9&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Contratante' or . = 'Contratante')]</value>
      <webElementGuid>eea64689-613c-4a0f-aad8-3a3c029ba281</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
