<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODY            PEsta pgina utiliza frame, pero su BROWSER no lo soportaP        BODY_fraFolder</name>
   <tag></tag>
   <elementGuidId>570f7fe1-bf56-4593-b7dc-14bf67725e9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>16720049-8ef2-456d-bc55-8a7095854be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>2c930450-d10a-4d07-a8a2-75f57ffbbbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Blank.aspx</value>
      <webElementGuid>b6d9e4dd-2c85-44f6-bc1f-2fd2c3f3128d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[2]/frame[2]</value>
      <webElementGuid>31c20816-25ce-497e-a25b-aad467339dab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>a18a9de2-9bf1-4d79-b891-a7d0a205bf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset[2]/frame[2]</value>
      <webElementGuid>415503b3-6cd3-493d-a58e-11505d6c19f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'Blank.aspx']</value>
      <webElementGuid>94b17578-840d-4fb4-8574-98607ffb850e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
