<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnCheckA</name>
   <tag></tag>
   <elementGuidId>4c4ca81d-ec0c-41f0-837b-dd6371c5bfb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#A390LI > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='if(insDisabledButton(document.A390,0)){ ClientRequest(390,2);}; return false']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d3153ee-12df-44f7-8824-cc375f01ef81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>abc47155-6a3f-4d48-b701-c815e8717dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(insDisabledButton(document.A390,0)){ ClientRequest(390,2);}; return false</value>
      <webElementGuid>13fdfc23-2992-4b25-92ad-ba62f5834ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>insChangeImage(&quot;A390&quot;,1)</value>
      <webElementGuid>978e9d77-17a3-4b1d-b42b-27f9ff256bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>insChangeImage(&quot;A390&quot;,2)</value>
      <webElementGuid>512054c7-f0ef-49bf-a9bb-ef1d0f6e353b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;A390LI&quot;)/a[1]</value>
      <webElementGuid>64979384-fa52-4353-9d1e-b93788963c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Coberturas de una pliza/frame_BODY            PEsta pgina utiliza frame, pero su BROWSER no lo soportaP        BODY_fraHeader</value>
      <webElementGuid>d4430af4-b9e4-43b8-b9bc-35d1e38ce3cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='if(insDisabledButton(document.A390,0)){ ClientRequest(390,2);}; return false']</value>
      <webElementGuid>eee03b16-24fd-4856-b8aa-5f7a0eb4f50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='A390LI']/a</value>
      <webElementGuid>cc32ced3-4f4b-441e-85c3-8ec5d7099197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ramo'])[1]/preceding::a[4]</value>
      <webElementGuid>a7378964-0e8d-4a66-96be-a0b11ce0ecc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Robo y riesgos similares'])[1]/preceding::a[4]</value>
      <webElementGuid>ebdb0684-7e0a-49b0-92f6-c2a44f0b26a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>f3aa270e-b133-45d0-9adb-bd3747593f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[3]/a</value>
      <webElementGuid>e9b9f8da-35b3-4039-bce0-58a535bc7cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>25278113-b040-42fe-8e56-3f4d8f8ed91a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
