<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODY            PEsta pgina utiliza frame, pero su BROWSER no lo soportaP        BODY_fraHeader</name>
   <tag></tag>
   <elementGuidId>9e566d61-ff8d-4895-9b3d-e7f8c0a05a14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraHeader&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>86121bc0-a930-4585-ab70-c54e07fc4a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraHeader</value>
      <webElementGuid>3852f9db-c1c0-44df-bf8d-0f93dbf2fb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>729c724c-d954-42dc-ba01-1420a1feb28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1184a95c-7af3-45da-8def-246cb5b1a900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>59b83246-ec6c-454d-9da6-f75f754cdd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Policy/PolicySeq/CA001_K.aspx?sConfig=InSequence&amp;LoadWithAction=&amp;bMenu=1&amp;sCodispl=CA001</value>
      <webElementGuid>4dfe65e8-ff64-4d45-b6cb-1d4ff00c3940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[2]/frame[1]</value>
      <webElementGuid>a674f6ad-1c97-4390-b9be-d56ea264900a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraHeader']</value>
      <webElementGuid>af852e13-8149-4f49-b712-fc0e0daa4946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset[2]/frame</value>
      <webElementGuid>74004c32-9278-4aa8-bb26-2cf52235622a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraHeader' and @src = '../Policy/PolicySeq/CA001_K.aspx?sConfig=InSequence&amp;LoadWithAction=&amp;bMenu=1&amp;sCodispl=CA001']</value>
      <webElementGuid>63a0bb29-6fd3-4d72-9090-b9b03fbbe317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
