<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Titular_btntctClient</name>
   <tag></tag>
   <elementGuidId>bd1c0183-9d87-4e5c-b30b-1608b61114ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btntctClient</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='btntctClient']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cf510cf5-05c6-4338-9dd7-7c0d327cffa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7cc87f5f-eeff-47a0-a3c3-07e0fae476f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/FindClientOn.png</value>
      <webElementGuid>a34678f0-f30e-4c1a-bc08-1008116b5470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>3c461e03-0f36-487c-bfc0-a112e11b8077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btntctClient</value>
      <webElementGuid>4e565ebf-a9b0-4452-81a4-ffe04b8ce299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btntctClient</value>
      <webElementGuid>8f4274bf-e811-45a8-b51a-8eeb428960b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Código que identifica al titular del recibo</value>
      <webElementGuid>3abec9a4-e00f-4881-80cf-1066a0356091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Código que identifica al titular del recibo</value>
      <webElementGuid>fed6608c-3ec3-4432-8283-bdf04f05781e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>MouseMoveImage(this, true)</value>
      <webElementGuid>19e7f728-6956-412d-b864-fea3c9c0aa42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>MouseMoveImage(this, false)</value>
      <webElementGuid>85871a3c-d094-463e-9775-0bfc79299588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btntctClient&quot;)</value>
      <webElementGuid>4b59739c-6bad-4370-a70c-57c9a06aefd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Datos/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>e0e6a9ca-0966-4ed6-a915-e994fc0845d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='btntctClient']</value>
      <webElementGuid>ac630c39-6912-415b-b5d5-edaec27c0745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[10]/td[2]/table/tbody/tr/td/a/img</value>
      <webElementGuid>db00df5d-396e-4e9d-bec6-b5e4270f7916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Código que identifica al titular del recibo']</value>
      <webElementGuid>02bca812-29e4-4d7d-8f85-23dfd76c8b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>4a8a2ec4-256e-4658-9333-36f6c762aaf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/FindClientOn.png' and @name = 'btntctClient' and @id = 'btntctClient' and @alt = 'Código que identifica al titular del recibo' and @title = 'Código que identifica al titular del recibo']</value>
      <webElementGuid>ca5a9cfd-a19f-4a56-9919-f523021e2920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
