<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Titular_tctClient</name>
   <tag></tag>
   <elementGuidId>f5e1a6af-d634-4dd7-bab7-49b2b5e96698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tctClient&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tctClient']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abff5392-7ef2-4cfa-9b0d-5a36ee897785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>74fdc298-1f64-4b60-980f-b510e5f7088c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tctClient</value>
      <webElementGuid>e3cd953c-b033-4fef-8275-5f0501c36e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>373a176b-23f8-4df6-b7a6-e51773c1dcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>76dd3c92-9767-4861-b601-f471032e3a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>5da17951-d1c2-40fa-99a0-199475e93f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Código que identifica al titular del recibo</value>
      <webElementGuid>2222bd2f-a6fa-4cde-8b23-acc424e55af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>tctClient.IsReq=0;tctClient.Alias=&quot;Código que identifica al titular del recibo&quot;;tctClient.Maxlength=14;if(ValText(tctClient,&quot;&quot;,&quot;False&quot;)){if (tctClient_Old.value != tctClient.value){ValidateClient(this,&quot;tctClient_Name&quot;,false,2,&quot;&quot;,1,&quot;&amp;sCertype=2&amp;nBranch=9&amp;nProduct=9100&amp;nPolicy=109078960&amp;nCertif=0&amp;dEffecdate=23/02/2023&amp;sOnChange=&quot;,false);};}</value>
      <webElementGuid>ced767f8-8dc0-4e58-8d22-4db4f3c5314c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[1]/tbody[1]/tr[10]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>d2bdd851-9b28-4bd5-9066-8d613cca1bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Datos/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>c93444d6-66cd-404b-befb-3ee9ae05598c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tctClient']</value>
      <webElementGuid>87c20fcc-97fb-49c3-9925-9dd599f2e2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[10]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>0ad0d71f-1cff-4cbe-a667-61abff90d742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>83c5af22-47a1-4987-99cc-c7f2f7ef7743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'tctClient' and @title = 'Código que identifica al titular del recibo']</value>
      <webElementGuid>0289ca8c-2d35-41b2-a60a-bd52ada1c351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
