<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Convenio colectivo_valgroup_Agree</name>
   <tag></tag>
   <elementGuidId>f77f7e7e-9855-4eb1-b7f7-296b3b04c1ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;valgroup_Agree&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='valgroup_Agree']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c747e5ac-8d0e-46c6-86ec-73d480538f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>d0006ebf-bf97-4904-8b8b-f797b814a5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>valgroup_Agree</value>
      <webElementGuid>12b64e63-47fb-40b5-823a-cfe0abcbf8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5c5bfd3a-bb08-4643-88f4-3e01d4468efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ead5eb3a-f570-4d4c-a409-5bba30df3f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>60a579ef-61a5-45b7-aa0f-d4bed488007e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Código del convenio colectivo asociado a la póliza en tratamiento</value>
      <webElementGuid>32e6b60d-984e-44d6-9d4f-c9118f7f28a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>self.document.forms[0].valgroup_Agree.HolePlace='05'; self.document.forms[0].valgroup_Agree.IsReq=0; self.document.forms[0].valgroup_Agree.ShowThousand=0; self.document.forms[0].valgroup_Agree.Alias='Código del convenio colectivo asociado a la póliza en tratamiento'; self.document.forms[0].valgroup_Agree.DecimalPlace=00;if(ValNumber(this,'.',',','false',0)){ShowValues(this,true,true,false);;}</value>
      <webElementGuid>a4cd5641-5cb3-4c7a-bbde-58afe88a8f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[1]/tbody[1]/tr[40]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>f1ad34eb-1819-4792-9b30-5a0fc0a57857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Datos/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>75fc0c7f-0b27-45d3-aba1-ec1757aff819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='valgroup_Agree']</value>
      <webElementGuid>ff8dedf2-2c3b-4b54-ba86-acff1a6dbb50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[40]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>afba2826-69d3-4c33-9b42-0b0103b0b344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[40]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>a79e5b82-cc85-498a-8ad9-e9781ff27522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'valgroup_Agree' and @title = 'Código del convenio colectivo asociado a la póliza en tratamiento']</value>
      <webElementGuid>377d9224-1468-4f30-89ff-bd883ba2bdf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
