<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Convenio_valAgreement</name>
   <tag></tag>
   <elementGuidId>af62b7ce-607f-4180-bae2-19fef303e035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;valAgreement&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='valAgreement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a53594b8-ac21-4cc2-8315-71ef38baf5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>6c11f94d-e1b6-44fb-9330-54b7bcdbef86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>valAgreement</value>
      <webElementGuid>11304780-1a60-4632-82be-bb1b9bf1d60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>42fae272-d603-40b8-b5e3-992057ede42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d88e9511-2675-4756-ba88-73099bf189bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>018c2960-1e24-434f-8f26-0a3046c450c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Convenio de pago y/o descuento asociado a la póliza</value>
      <webElementGuid>c058f396-b04f-4077-9cd4-55ee5b75f9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>self.document.forms[0].valAgreement.HolePlace='05'; self.document.forms[0].valAgreement.IsReq=0; self.document.forms[0].valAgreement.ShowThousand=0; self.document.forms[0].valAgreement.Alias='Convenio de pago y/o descuento asociado a la póliza'; self.document.forms[0].valAgreement.DecimalPlace=00;if(ValNumber(this,'.',',','false',0)){ShowValues(this,true,true,false);InsChangeAgreement();;}</value>
      <webElementGuid>bde96c42-33c0-40bb-8f57-fb2d3b9a72a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[1]/tbody[1]/tr[28]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>4916b3fa-c675-4251-8b8a-e7282e49442f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Datos/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>0d5fa333-9cc4-47cd-8316-0c1dc32ba096</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='valAgreement']</value>
      <webElementGuid>5f0ea5a9-52f9-4411-937b-e07f5e6e9c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[28]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>4550363b-c872-46bc-8ed8-33d40c9a34eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[28]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>073d1f3b-e26c-4978-823d-2c042549c580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'valAgreement' and @title = 'Convenio de pago y/o descuento asociado a la póliza']</value>
      <webElementGuid>b325ed98-b162-419b-b753-edcc43d6847d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
