<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero de comercio_valCommernum</name>
   <tag></tag>
   <elementGuidId>8ccc7ce1-5d4d-4fd7-9c6e-b984142b2562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;valCommernum&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='valCommernum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>963b368e-cc8a-4816-950e-f9d58d45f9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>279a1feb-399c-4ee2-a36a-c0eee58edd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>valCommernum</value>
      <webElementGuid>7eea8487-900e-4013-bbda-c4d5373983da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>51a87ac2-dade-40d8-93e6-11333729c5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>009d0594-f199-4e66-9d63-2728bb4f310a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>89bfbdb0-0f33-4074-a931-2cfa7e4ee6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Número de comercio</value>
      <webElementGuid>015a0e85-7490-497b-9ec6-0de15c77a685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>self.document.forms[0].valCommernum.HolePlace='012'; self.document.forms[0].valCommernum.IsReq=0; self.document.forms[0].valCommernum.ShowThousand=0; self.document.forms[0].valCommernum.Alias='Número de comercio'; self.document.forms[0].valCommernum.DecimalPlace=00;if(ValNumber(this,'.',',','false',0)){ShowValues(this,true,true,false);;}</value>
      <webElementGuid>254981a8-2bc4-4546-a9ab-ee7752869ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[1]/tbody[1]/tr[29]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>0deff7f2-b82b-46ca-9234-1e13fb8adc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Datos/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>f4ba83b0-fbc1-4519-b529-4f7a5f636376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='valCommernum']</value>
      <webElementGuid>4449fa6a-36e1-4c78-898b-fe3836a7b7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[29]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>6753286c-d1df-4007-8691-db6a7d0f8adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[29]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>61dbb0ce-bd9d-4730-8e8a-dcf541b0aa04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'valCommernum' and @title = 'Número de comercio']</value>
      <webElementGuid>3d16b09d-4871-4035-b687-ac1ef8acd2e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
