<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Facturacin vencidaNo AplicaFacturaci_fc9188</name>
   <tag></tag>
   <elementGuidId>eb6f95f6-40f0-45ae-8377-faa1d9db4eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;cbeBill_ind&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='cbeBill_ind']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7303830e-5b24-4546-b2dd-69dfa4854cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbeBill_ind</value>
      <webElementGuid>21f4ae2a-abd9-4271-9e88-acec8bb2234d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>d7d246bf-0eb5-4b77-8f1b-a627ec53c809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Indicador de factura</value>
      <webElementGuid>ae4c2218-5c8f-4b07-9ece-cd9d09e0a29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Facturación vencidaNo AplicaFacturación anticipada</value>
      <webElementGuid>7dfa7324-5554-4c31-bc63-d95ee1694b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[1]/tbody[1]/tr[18]/td[2]/select[1]</value>
      <webElementGuid>45b6171a-9e19-428c-a14b-5173b4ad35e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  Datos/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>73f946e7-c37c-4447-b5f8-2f4f11e17cf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='cbeBill_ind']</value>
      <webElementGuid>e72c4b27-7dd4-4cdb-bf3a-224eecd79c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[18]/td[2]/select</value>
      <webElementGuid>e6933645-eeb9-42cc-93ba-72939cd69b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indicador de factura'])[1]/following::select[1]</value>
      <webElementGuid>f779b39e-e374-41e9-9b98-f3f951e05554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha revalorización'])[1]/preceding::select[1]</value>
      <webElementGuid>68796c21-4a43-4940-bf3e-ae516d3367ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indicador de generación de recibo'])[1]/preceding::select[1]</value>
      <webElementGuid>f50b80ae-5a26-4a87-8604-0dc2d50cbf1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[2]/select</value>
      <webElementGuid>1de82aaf-68e6-4faf-8958-e920750ca534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cbeBill_ind' and @title = 'Indicador de factura' and (text() = 'Facturación vencidaNo AplicaFacturación anticipada' or . = 'Facturación vencidaNo AplicaFacturación anticipada')]</value>
      <webElementGuid>8dc7a0e5-8876-4422-8164-e2633ee561f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
