<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODY  PEsta pgina usa marcos, pero su explorador no los admite.P  BODY_fraFolder</name>
   <tag></tag>
   <elementGuidId>05e8e9ed-b184-4321-9314-b6106ad70ffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>b595b898-b978-4c89-b4d7-1085c7dfa774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>framespacing</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4e47a6ec-778c-45e5-9d27-8af81d9675c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>819d5a1c-889f-4a39-ab2e-965be695e8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>d15e62ac-c937-44f5-9d5f-1e8acb39ee40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e075ab1-679e-4f00-b4ed-2b2ba53772b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraGeneric</value>
      <webElementGuid>0b5a9f72-3cfd-409d-bcfd-f2cd6e2f3b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/VTimeNet/Policy/PolicySeq/CA050.aspx?sPageName=/VTimeNet/Policy/PolicySeq/CA050&amp;nAction=392</value>
      <webElementGuid>2619b27f-6260-45f3-81b1-8d3fba4a8c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>e5456e9d-429e-4f8b-8e30-2c39639706cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>b06fa23e-4c0e-4c0c-a92a-2fe021bfbb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>bb1642b5-65ef-4105-9613-38b9a210e47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = '/VTimeNet/Policy/PolicySeq/CA050.aspx?sPageName=/VTimeNet/Policy/PolicySeq/CA050&amp;nAction=392']</value>
      <webElementGuid>c1619115-3c6d-440b-9de3-35f5dd3a7658</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
