<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero_valcredi_card</name>
   <tag></tag>
   <elementGuidId>7fe906fa-b6e8-423d-a28d-973f06dde020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;valcredi_card&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='valcredi_card']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>682e72d5-3f40-46b4-9939-74f4133c6e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>796579c7-195b-4784-997a-98279b2e02c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>valcredi_card</value>
      <webElementGuid>a610d1a9-1114-4a96-83f4-015acb89c755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>0934e41a-5f15-4a1b-8f5c-bdc2bbc78c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6fc5d7d7-78be-407c-838b-441d9758a202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>50720c9d-43ed-49c6-8663-dbb857f7c4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Número de la tarjeta de crédito</value>
      <webElementGuid>bfb04397-ecb1-4154-a19e-2ee148b5eda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>valcredi_card.IsReq=0;valcredi_card.Alias=&quot;Número de la tarjeta de crédito&quot;;valcredi_card.Maxlength=20;if(ValText(valcredi_card,&quot;&quot;,&quot;False&quot;)){ShowValues(this,true,false,true);InsChangecredi_card();;}</value>
      <webElementGuid>b966055b-c059-447c-86d2-9dd56e3aefb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[19]/td[5]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>32380699-42d5-4009-856d-1353af37e7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  V/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>f6abd5ed-246e-46a9-a2c2-46f4984566d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='valcredi_card']</value>
      <webElementGuid>f0b0c75d-d6a9-4375-97dd-fe84a17173a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[5]/table/tbody/tr/td/input</value>
      <webElementGuid>fbba7ad4-7f68-46ab-bf8f-fe7981ad0c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'valcredi_card' and @title = 'Número de la tarjeta de crédito']</value>
      <webElementGuid>8f48fa45-f2fd-4c43-9c31-68ede46cf14c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
