<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha de vencimiento_tcdDateExpir</name>
   <tag></tag>
   <elementGuidId>d2de23a3-21e0-47b3-9a87-d2c92cad8ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dp1677184298113</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dp1677184298113']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a7d326d-a741-4f37-9e5c-5b0b4d77233f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker hasDatepicker</value>
      <webElementGuid>fe2ff1fd-6e4c-4dfd-bb8e-206ab480bc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>955189f4-86c5-4ef6-98a7-53d6c81647d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tcdDateExpir</value>
      <webElementGuid>1291e350-8d50-44b4-ae6f-68540e51d5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c2519c62-e465-4601-b40b-f4ace2f6ef94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c7bba321-e412-457e-abaa-f631c0fa7be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Fecha de vencimiento de la tarjeta de crédito</value>
      <webElementGuid>66f403ce-3adb-41e5-9975-7f5b93df34b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9342e892-2ca9-4d97-a6be-6cf778026606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>tcdDateExpir.IsReq=0;tcdDateExpir.Alias=&quot;Fecha de vencimiento de la tarjeta de crédito&quot;;if(ValDate(tcdDateExpir , &quot;DD/MM/YYYY&quot; , &quot;/&quot;)){}</value>
      <webElementGuid>f43dc906-02e0-41da-9e51-3a5fd3750aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp1677184298113</value>
      <webElementGuid>e1040c0b-d9ff-48fc-ad7c-7504e491a7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp1677184298113&quot;)</value>
      <webElementGuid>a99d7e24-a781-40ab-8a49-291ad3c72509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  V/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>cb31e62b-b35f-4375-a31c-d55c1c36b652</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp1677184298113']</value>
      <webElementGuid>f40b6fa4-33f6-4bbe-a723-e2e59b33dca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td[2]/input</value>
      <webElementGuid>9028ad64-ab34-49bb-bb23-7f8d75e4fc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'tcdDateExpir' and @title = 'Fecha de vencimiento de la tarjeta de crédito' and @id = 'dp1677184298113']</value>
      <webElementGuid>3881a9fc-8123-4af4-bcb8-4f0e9846ad2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
