<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODY</name>
   <tag></tag>
   <elementGuidId>3084f24b-e5a2-4938-9be3-8b938182e8ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>d59ddc12-bfdd-40a5-b9d5-adb838185234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>framespacing</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>90287082-a8fe-4a6d-a64e-98ab55058339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>f5c7842b-e15f-47a4-91ed-abeea2c4b0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>7435886a-76c0-49aa-9f07-6cdb6ff3152b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>29c794f5-5768-4cff-a0e2-8df46d8469bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraGeneric</value>
      <webElementGuid>2e198530-1f9f-466d-9949-f785a96289d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>GridPopUp.aspx?Type=PopUp&amp;Action=Add&amp;Index=-1&amp;nMainAction=304&amp;sCodispl=CA013&amp;nCurrency=1&amp;nGroup=0&amp;sTyp_module=2</value>
      <webElementGuid>90f889d0-8464-4088-a65d-32b7e9b48472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>addc7897-2f52-4fe0-8ac8-a765a39daf8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>22341c6a-8780-4aa6-8ad4-883d9e5ba180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>43d218fc-6220-4143-8355-994db1e79ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'GridPopUp.aspx?Type=PopUp&amp;Action=Add&amp;Index=-1&amp;nMainAction=304&amp;sCodispl=CA013&amp;nCurrency=1&amp;nGroup=0&amp;sTyp_module=2']</value>
      <webElementGuid>d34088d0-f467-4225-81fb-928c24255580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
