<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Continuar_cmdAccept</name>
   <tag></tag>
   <elementGuidId>19f36512-2ffa-4dfe-977b-b92bdc20c2f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cmdAccept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cmdAccept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cd85ab9c-822a-40de-a0e9-b4c2078771af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b3c7bbda-d455-419b-b116-0807f7351229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnAcceptOn.png</value>
      <webElementGuid>6d9d7e0a-e658-4471-b9e3-e59674008b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cmdAccept</value>
      <webElementGuid>aa297539-edad-47d2-85a5-9477da29c992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmdAccept</value>
      <webElementGuid>a96124f3-90c5-44a1-aba3-ffbff339a2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Aceptar la información de la ventana</value>
      <webElementGuid>bc4a1aaf-6b90-4c53-a45f-2e3823aed2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aceptar la información de la ventana</value>
      <webElementGuid>3513fe0a-5dfc-4931-9ae4-1ee6bb6c4262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>MouseMoveImage(this, true)</value>
      <webElementGuid>d8da416a-b7cc-4242-95d5-2e198b7e9336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>MouseMoveImage(this, false)</value>
      <webElementGuid>fc4111bc-6938-4b9f-80d4-87655d1c85eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ToolbarHeaderHover</value>
      <webElementGuid>12c9eebe-9bee-41f7-a710-e2e7e7025d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmdAccept&quot;)</value>
      <webElementGuid>de887001-9329-4c06-956a-7bfbaee70128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Modulo/frame_BODY  PEsta pgina usa marcos, pero su explorador no los admite.P  BODY_fraFolder</value>
      <webElementGuid>5150a7f7-8144-4c55-96d6-5192686de87b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cmdAccept']</value>
      <webElementGuid>ef589b16-edb1-4e3a-9320-cdd0d16de886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Aceptar la información de la ventana']</value>
      <webElementGuid>f4dcf89a-978d-4c56-909f-613a7169110a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>b6483855-c329-498e-b0ad-a05791107f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnAcceptOn.png' and @name = 'cmdAccept' and @id = 'cmdAccept' and @alt = 'Aceptar la información de la ventana' and @title = 'Aceptar la información de la ventana']</value>
      <webElementGuid>3c37fcc2-7404-406e-8bdf-9f6d72ad64da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
