<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cdigo_valModulec</name>
   <tag></tag>
   <elementGuidId>29da61f0-e71e-458b-8cc7-7b95889e607a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;valModulec&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='valModulec']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>558a953e-694e-4244-9e72-129bd0771cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>d8dfb661-4e76-4c56-94e1-00a35f5f93f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>valModulec</value>
      <webElementGuid>b35f007b-dcd0-48e9-bf7b-acfd38a1e525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3d5ddb3b-e1cc-4919-8ead-e3335529776a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c873bc1d-214a-44f1-80e3-bc09b326ecb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>76ad550d-7612-44d2-a08e-e6869cb7246c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Código del módulo asociado a la póliza/certificado en tratamiento</value>
      <webElementGuid>d7baff5c-35dc-4ef8-b900-8385908633fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>self.document.forms[0].valModulec.HolePlace='05'; self.document.forms[0].valModulec.IsReq=0; self.document.forms[0].valModulec.ShowThousand=0; self.document.forms[0].valModulec.Alias='Código del módulo asociado a la póliza/certificado en tratamiento'; self.document.forms[0].valModulec.DecimalPlace=00;if(ValNumber(this,'.',',','false',0)){ShowValues(this,true,true,false);insHabilitate(this);;}</value>
      <webElementGuid>9a171789-21c1-4605-a1b7-dc5b72de025f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>44dd772b-e0ca-43ad-a10a-6876025bcecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Modulo/frame_BODY</value>
      <webElementGuid>a8c6ccb6-2e71-436a-aabe-207ae3605f3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='valModulec']</value>
      <webElementGuid>39c8f53a-e0ad-48ce-9914-e6e766cfac1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>11681983-e28c-4992-9533-6c8705023c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'valModulec' and @title = 'Código del módulo asociado a la póliza/certificado en tratamiento']</value>
      <webElementGuid>bd4e1314-a4ed-4256-832b-ad2367c791e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
