<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Mdulosdelapliza</name>
   <tag></tag>
   <elementGuidId>84158237-7e3b-421d-a5b9-fbf94ebc668b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Código'])[1]/preceding::h2[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d6f5eb53-6af6-4bd0-9798-8867bb18e10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Módulos de la póliza</value>
      <webElementGuid>f34b3f45-f959-49a9-896f-7ef3a1333a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/div[@class=&quot;DIVActionGrid&quot;]/div[@class=&quot;DIVWindowsName&quot;]/h2[1]</value>
      <webElementGuid>fae99505-ee49-4eb5-9b47-89de79dd12a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Modulo/frame_BODY_fraFolder</value>
      <webElementGuid>fcf981de-6f0e-4765-a47b-61813ed9d9ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código'])[1]/preceding::h2[1]</value>
      <webElementGuid>fbebf24a-e856-49da-aa7c-132c53d41a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambios'])[1]/preceding::h2[1]</value>
      <webElementGuid>ce57ad20-5cb6-4498-b9aa-24bf8cfdea26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Módulos de la póliza']/parent::*</value>
      <webElementGuid>96b76b82-4d1f-4ed6-840f-8a5c5df0f40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>9f5bc2be-6c37-481a-8cc5-4e6495b09b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Módulos de la póliza' or . = 'Módulos de la póliza')]</value>
      <webElementGuid>11ff76c9-15de-48ed-9840-c982558228f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
