<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODYCheck</name>
   <tag></tag>
   <elementGuidId>6401fde4-2b2b-4164-9228-6dff2f757b6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>1993534f-a5cf-4fed-8c79-c0949c12e959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>framespacing</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b263cbd1-e585-4ceb-a3a3-1ea8b03db51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>17892eb8-ce20-4cc2-b8a9-f23790fa7a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>bbbcc043-acbf-4ed6-8787-1956ad17f176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7dd6807d-7ec1-44c1-b67b-367e7ef4804d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraGeneric</value>
      <webElementGuid>3da28297-8043-4c9c-8673-2d388bd61503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=0&amp;nMainAction=304&amp;sCodispl=CA014&amp;nProdclas=0&amp;nAge=0&amp;nRole=2&amp;sClient=00000042933160&amp;sDisabledByLevels=2&amp;nIndexCover=&amp;nLegAmount=-32768&amp;VIP=&amp;sNopayroll=2&amp;nTypdurpay=6&amp;nTyperisk=-32768&amp;sCodisp=CA014&amp;sWindowDescript=Coberturas&amp;nWindowTy=9</value>
      <webElementGuid>130f74f1-261d-4f0a-a8c9-2c4c2f634676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>c8902f05-b460-45fc-9d76-2e3381fae3d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>03163a5e-e02f-48a2-9ff7-89bba56f28bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>4f6df41b-7123-4279-ad19-4fc803ff0a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=0&amp;nMainAction=304&amp;sCodispl=CA014&amp;nProdclas=0&amp;nAge=0&amp;nRole=2&amp;sClient=00000042933160&amp;sDisabledByLevels=2&amp;nIndexCover=&amp;nLegAmount=-32768&amp;VIP=&amp;sNopayroll=2&amp;nTypdurpay=6&amp;nTyperisk=-32768&amp;sCodisp=CA014&amp;sWindowDescript=Coberturas&amp;nWindowTy=9']</value>
      <webElementGuid>4cf287ff-5594-4f2e-8fbe-8849b8f77d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
