<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODYBODY_fraFolder</name>
   <tag></tag>
   <elementGuidId>e583e64b-fd8b-428b-ba67-0dea05ec3494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>167ae477-3526-4585-b40c-4adfe3837473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>framespacing</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>25819d55-15cf-4500-b9f6-f38077882267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>a2ad8d9b-f336-4fd6-bd90-366e096ab47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>50438811-f5d7-4b34-a641-6e6ed04948ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bec4b68b-7f74-4ff0-a1c8-8aeb83279703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraGeneric</value>
      <webElementGuid>529e31dc-5e2c-4815-be1a-e9949a6edc2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=0&amp;nMainAction=304&amp;sCodispl=CA014&amp;nProdclas=0&amp;nAge=0&amp;nRole=2&amp;sClient=00000042933160&amp;sDisabledByLevels=2&amp;nIndexCover=&amp;nLegAmount=-32768&amp;VIP=&amp;sNopayroll=2&amp;nTypdurpay=6&amp;nTyperisk=-32768&amp;sCodisp=CA014&amp;sWindowDescript=Coberturas&amp;nWindowTy=9</value>
      <webElementGuid>d695125a-2d9a-42c0-a098-b3ed2bbec2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>09924f06-3b0e-49fc-8491-8676e0cb3455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>e0a6493c-1329-42f2-9aaf-d278d9808e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>d40d1b28-bbdf-4a13-8c50-07145508a6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=0&amp;nMainAction=304&amp;sCodispl=CA014&amp;nProdclas=0&amp;nAge=0&amp;nRole=2&amp;sClient=00000042933160&amp;sDisabledByLevels=2&amp;nIndexCover=&amp;nLegAmount=-32768&amp;VIP=&amp;sNopayroll=2&amp;nTypdurpay=6&amp;nTyperisk=-32768&amp;sCodisp=CA014&amp;sWindowDescript=Coberturas&amp;nWindowTy=9']</value>
      <webElementGuid>1654c944-7d21-4f87-8158-36dfd156f2b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
