<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODYSumaAsegurada</name>
   <tag></tag>
   <elementGuidId>de4b423e-cfcd-4c55-8e7d-74bbae05a692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>548130d1-f3a6-4f3b-9859-c564baefaf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>framespacing</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>24a4c873-f32f-48aa-b3d3-756e72c5f00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>9482e126-3f36-410c-abe4-e33b14954a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>e5c3b152-d295-470b-988c-78eecd152d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>26550805-e7a1-40d2-a8cc-c984c84fd5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraGeneric</value>
      <webElementGuid>d86a6887-e80e-4ec4-8818-cade63238acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=0&amp;nMainAction=304&amp;sCodispl=CA014&amp;nProdclas=0&amp;nAge=0&amp;nRole=2&amp;sClient=00000042933160&amp;sDisabledByLevels=2&amp;nIndexCover=&amp;nLegAmount=-32768&amp;VIP=&amp;sNopayroll=2&amp;nTypdurpay=6&amp;nTyperisk=-32768&amp;sCodisp=CA014&amp;sWindowDescript=Coberturas&amp;nWindowTy=9</value>
      <webElementGuid>6214f4f3-2b38-41be-9922-41d7d37cbe6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>688c59df-26a0-488c-97e0-98bf452931af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>61965aee-b456-48d8-af03-b5af0b3b7246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>cbae8585-5e3f-4717-ad7c-ab5368759b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=0&amp;nMainAction=304&amp;sCodispl=CA014&amp;nProdclas=0&amp;nAge=0&amp;nRole=2&amp;sClient=00000042933160&amp;sDisabledByLevels=2&amp;nIndexCover=&amp;nLegAmount=-32768&amp;VIP=&amp;sNopayroll=2&amp;nTypdurpay=6&amp;nTyperisk=-32768&amp;sCodisp=CA014&amp;sWindowDescript=Coberturas&amp;nWindowTy=9']</value>
      <webElementGuid>7dfe74ce-a62d-4898-840c-b26354da2634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
