<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suma asegurada_tcnCapital</name>
   <tag></tag>
   <elementGuidId>6125aeab-4734-4cea-a093-aa8de519d822</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tcnCapital&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tcnCapital']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d55834e-ab6b-452a-8987-2ccfd4735d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>a34ee0ce-c56d-41ff-9854-072a96b0bc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tcnCapital</value>
      <webElementGuid>487f7241-9feb-424a-8111-d7644c242338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>f18ad753-ee3a-4e31-96f9-cb772f97af41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>f72d6c00-5f9a-4fce-ba88-dabe97266b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>137fee98-26b0-468a-926c-e2b437a0c6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Capital asegurado</value>
      <webElementGuid>a0b4c27c-48fd-427a-9668-6613d711e9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0,000000</value>
      <webElementGuid>561a40cd-3805-4511-9101-638033fa920a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>self.document.forms[0].tcnCapital.HolePlace='012'; self.document.forms[0].tcnCapital.IsReq=1; self.document.forms[0].tcnCapital.ShowThousand=1; self.document.forms[0].tcnCapital.Alias='Capital asegurado'; self.document.forms[0].tcnCapital.DecimalPlace=06;if(ValNumber(this,'.',',','false',6)){insCalPremium('1');}</value>
      <webElementGuid>4a4f1282-4182-4d2b-a29c-c224bb5fac26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[1]/tbody[1]/tr[6]/td[2]/input[1]</value>
      <webElementGuid>10f386a8-27b1-4637-9cee-d979801b42aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Cobertura/frame_BODYSumaAsegurada</value>
      <webElementGuid>d58ca0b8-2cc3-42de-9e7d-fcc20f7fefed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tcnCapital']</value>
      <webElementGuid>5b0c6e66-e7b5-4d9a-8b04-0a67eb9bf6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>70c30f90-7c9b-4c1e-b62c-5984ba142c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>ef6836bf-a99d-49a0-a12d-5c85f0940e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'tcnCapital' and @title = 'Capital asegurado']</value>
      <webElementGuid>19d362ee-6ac9-41f0-80bd-16b740c6b538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
