<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODYCheck</name>
   <tag></tag>
   <elementGuidId>a2693fff-af4f-49e8-81e6-4cf8e79c7b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>73d4d6f5-f561-4085-b771-a32e54408de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>framespacing</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>09157495-ac3e-4208-a219-5d461dce8713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>21e192a8-2f1b-4fb2-9c75-b30b0fdfee9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>e4c02920-29fc-4112-8ca2-000c9d4fe345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b4d20701-e462-4745-9f32-5666dab9cc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraGeneric</value>
      <webElementGuid>0db5f6a9-2396-49cc-9a56-5ba38dbda8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=1&amp;nMainAction=0&amp;sCodispl=CA016&amp;nGroup=0&amp;sTyp_discxp=2&amp;nPage=1&amp;sCodisp=CA016&amp;sWindowDescript=Recargos/descuentos/impuestos%C2%A0-%C2%A0P%C3%B3liza%C2%A0individual/certif&amp;nWindowTy=9</value>
      <webElementGuid>0d8ad90a-fe55-45cf-8ee5-694fa1168f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>cddba5d2-c59a-4c04-8889-ed5407e99b6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>c73231ed-ebd0-4fba-8ed6-f873652f5a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>1102c0a3-801e-4d2f-94d8-46f84bda490c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=1&amp;nMainAction=0&amp;sCodispl=CA016&amp;nGroup=0&amp;sTyp_discxp=2&amp;nPage=1&amp;sCodisp=CA016&amp;sWindowDescript=Recargos/descuentos/impuestos%C2%A0-%C2%A0P%C3%B3liza%C2%A0individual/certif&amp;nWindowTy=9']</value>
      <webElementGuid>e7807835-6d88-49e7-b70a-1ad0738762fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
