<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODYLabel</name>
   <tag></tag>
   <elementGuidId>5e603a08-d334-4ac1-bd99-571b052bc472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>38ece54b-ec77-41a9-9a22-5aabc68892b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>framespacing</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>81ab4a18-a119-4fab-8013-b92c73f9fdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>e9ab808a-d6f8-4759-83e8-4ca16d293ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>997acd85-e69c-4e01-843b-648bcd040f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fb28434d-bcc6-444f-90ff-efff62027dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraGeneric</value>
      <webElementGuid>66f480c7-5932-4ab1-aabe-aa77f8a65fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=1&amp;nMainAction=0&amp;sCodispl=CA016&amp;nGroup=0&amp;sTyp_discxp=2&amp;nPage=1&amp;sCodisp=CA016&amp;sWindowDescript=Recargos/descuentos/impuestos%C2%A0-%C2%A0P%C3%B3liza%C2%A0individual/certif&amp;nWindowTy=9</value>
      <webElementGuid>09ff9a12-2f89-4624-9625-03a023f889be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>9ab92d72-e62b-48c3-9d04-fb14dc8293e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>64d6ffff-b322-4897-840e-665ccc7b4ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>315c8bcc-8172-4d0c-8d28-7fd0f9b4fecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=1&amp;nMainAction=0&amp;sCodispl=CA016&amp;nGroup=0&amp;sTyp_discxp=2&amp;nPage=1&amp;sCodisp=CA016&amp;sWindowDescript=Recargos/descuentos/impuestos%C2%A0-%C2%A0P%C3%B3liza%C2%A0individual/certif&amp;nWindowTy=9']</value>
      <webElementGuid>b13b95fc-d197-4179-b82b-01a530c28bed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
