<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODYFactor</name>
   <tag></tag>
   <elementGuidId>dd751833-6cfe-43e2-a870-111f04ed7262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>ff6683a3-aabf-4479-a338-dfce6952b825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>framespacing</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ca9319c0-3ec0-4f3f-954c-f3689f519e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>f6c18672-e507-4c25-97fc-6d094250f667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>2aa4a4fa-fc95-4a6a-b0a8-16829c4b4467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24ba6eab-2849-452c-ab35-29106ea6f4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraGeneric</value>
      <webElementGuid>492ae211-51f4-4354-9c78-27e9e421b53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=1&amp;nMainAction=0&amp;sCodispl=CA016&amp;nGroup=0&amp;sTyp_discxp=2&amp;nPage=1&amp;sCodisp=CA016&amp;sWindowDescript=Recargos/descuentos/impuestos%C2%A0-%C2%A0P%C3%B3liza%C2%A0individual/certif&amp;nWindowTy=9</value>
      <webElementGuid>e31be4ab-523a-4127-ac6a-79dd3ed5bfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>8934f425-a1c7-49fd-ba2f-0e30c3bce834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>5d474678-2ff5-4827-9f6c-c9d54d7d9e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>19e53f11-1a05-4414-a2ff-52ace4e1e0ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'GridPopUp.aspx?Type=PopUp&amp;Action=Update&amp;Index=1&amp;nMainAction=0&amp;sCodispl=CA016&amp;nGroup=0&amp;sTyp_discxp=2&amp;nPage=1&amp;sCodisp=CA016&amp;sWindowDescript=Recargos/descuentos/impuestos%C2%A0-%C2%A0P%C3%B3liza%C2%A0individual/certif&amp;nWindowTy=9']</value>
      <webElementGuid>6aa000ff-adc5-4de7-9235-5b9ff46aad13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
