<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Continuar_cmdAccept</name>
   <tag></tag>
   <elementGuidId>9f6abcc2-3136-4c63-91dd-5cb5f6594e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cmdAccept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cmdAccept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e2fcfee7-1a93-4ac4-951b-a8cc4987c220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>018b4574-caf9-41f5-8d8a-198870be3190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnAcceptOn.png</value>
      <webElementGuid>cc781096-edb4-4bc0-a2a3-c46c45bf3177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cmdAccept</value>
      <webElementGuid>c87a82bf-f012-4b36-99fc-49c7e2b42468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmdAccept</value>
      <webElementGuid>4738c900-2ee6-4e49-9a04-dfb700167cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Aceptar la información de la ventana</value>
      <webElementGuid>d1073e80-da88-4bd4-b7b7-4330a0d1eac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aceptar la información de la ventana</value>
      <webElementGuid>09fe70de-bc95-43cd-b233-18fba58778f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>MouseMoveImage(this, true)</value>
      <webElementGuid>b6bcd6db-e3c9-48fa-96a1-66aca9d00687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>MouseMoveImage(this, false)</value>
      <webElementGuid>9e9c41dd-2f0a-4b0d-adcc-71a67fabe0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ToolbarHeaderHover</value>
      <webElementGuid>5bea002c-3a75-40ed-9dcf-1aa5c7144b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmdAccept&quot;)</value>
      <webElementGuid>830bd003-d2c9-4d0f-b856-a2b79c04ffe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Descuentos/frame_BODYCheck</value>
      <webElementGuid>215d13aa-8cd5-48a7-8c6e-3eb7964ce100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cmdAccept']</value>
      <webElementGuid>c0fc0aa4-54eb-46f5-ad36-3f2fca3172da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Aceptar la información de la ventana']</value>
      <webElementGuid>a6f69b8d-2516-49f1-8708-d62d30c902a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ba1d844b-ad9f-48c3-84c0-4b29bd975a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/Images/btnAcceptOn.png' and @name = 'cmdAccept' and @id = 'cmdAccept' and @alt = 'Aceptar la información de la ventana' and @title = 'Aceptar la información de la ventana']</value>
      <webElementGuid>214fc92d-e0ce-405d-8c38-1532e6487f3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
