<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Factor_tcnPercent</name>
   <tag></tag>
   <elementGuidId>0030d06e-bfea-4f31-a1a8-c5414e828777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tcnPercent&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tcnPercent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb7846e5-1d5d-4d44-9b5b-ebc84e801d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>6840fae8-b4fc-43cd-8fbf-265cbf836322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tcnPercent</value>
      <webElementGuid>b9825e04-88a7-4857-be51-0b18c78f4c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>989c89d2-c600-43f5-b538-1641034d2e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c27c62f7-5534-479e-a4b8-d224b7b9a71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a7b691ea-7ce6-47fe-9b99-498ffff8d77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Factor de cálculo a aplicar para obtener el monto del elemento</value>
      <webElementGuid>38a71384-4275-4f16-af7d-9a00c6007b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>self.document.forms[0].tcnPercent.HolePlace='03'; self.document.forms[0].tcnPercent.IsReq=0; self.document.forms[0].tcnPercent.ShowThousand=0; self.document.forms[0].tcnPercent.Alias='Factor de cálculo a aplicar para obtener el monto del elemento'; self.document.forms[0].tcnPercent.DecimalPlace=06;if(ValNumber(this,'.',',','false',6)){}</value>
      <webElementGuid>6eced778-c941-4d9b-bc59-e16210ac2009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[4]/td[2]/input[1]</value>
      <webElementGuid>019f28ab-1749-434c-92fb-04b3a625b83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Descuentos/frame_BODYFactor</value>
      <webElementGuid>afc18f61-3bd3-4034-9b96-4fe601ccd266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tcnPercent']</value>
      <webElementGuid>c6b1aa5d-efea-4531-821a-4c883397d093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>a34d774d-e6b2-4bd6-87c3-d7fbee2f3d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'tcnPercent' and @title = 'Factor de cálculo a aplicar para obtener el monto del elemento']</value>
      <webElementGuid>d3c7a389-5497-4315-82ac-350855c4028b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
