<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODY            PEsta pgina utiliza f_69e94c</name>
   <tag></tag>
   <elementGuidId>0a23e837-7a07-4977-941e-a1056678184b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraHeader&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>d4bf0fbb-6c9d-419b-9e11-2d5747ccb5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraHeader</value>
      <webElementGuid>98e2dcb4-cabe-4336-8b1a-10f08de9aa3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>06b16c6c-1131-4fb5-ad00-e3c453ee8ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fdd5f901-2a98-4b06-9db3-7d250a489152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>4349b4df-7158-4260-8272-231b485eb443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Policy/PolicySeq/CA001_K.aspx?sConfig=InSequence&amp;LoadWithAction=&amp;bMenu=1&amp;sCodispl=CA001</value>
      <webElementGuid>ecf3ff24-b87d-4dd2-997f-79e3ff0857f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[2]/frame[1]</value>
      <webElementGuid>9397270f-c82f-4a98-a9b3-1648077dda0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraHeader']</value>
      <webElementGuid>bcaa930b-ecc1-4109-aafb-c7a70b0e5a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset[2]/frame</value>
      <webElementGuid>3fcece2e-1d5b-4bd6-a0f2-92cf75a1e079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraHeader' and @src = '../Policy/PolicySeq/CA001_K.aspx?sConfig=InSequence&amp;LoadWithAction=&amp;bMenu=1&amp;sCodispl=CA001']</value>
      <webElementGuid>710f0c36-4d55-412a-892c-aae81ab03cb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
