<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Plan de comisin_btnvalCommPlan</name>
   <tag></tag>
   <elementGuidId>a8d521b7-4c72-439a-abcf-b38249cc99b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnvalCommPlan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='btnvalCommPlan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5246f5f6-6938-4d6e-9085-cb9872e1ea5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ff9e2ce2-38ab-4e59-9e2c-421fb8ad97f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/images/btn_ValuesOn.png</value>
      <webElementGuid>f1fee791-677d-4cfa-be12-476f156fd49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnvalCommPlan</value>
      <webElementGuid>e9092681-7e2c-4383-a083-61553cd6e98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnvalCommPlan</value>
      <webElementGuid>919ed901-305e-44d7-8e45-ac7d798ed36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Código del plan de comisiones de la póliza o certificado (Valores posibles)</value>
      <webElementGuid>97c91476-c654-42ad-b980-13b02d05ed3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Código del plan de comisiones de la póliza o certificado (Valores posibles)</value>
      <webElementGuid>f3332136-a310-4c01-ab15-05b162505122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>MouseMoveImage(this, true)</value>
      <webElementGuid>33556dd2-3fe7-4157-98c4-6e383cf8e6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>MouseMoveImage(this, false)</value>
      <webElementGuid>5126269f-8076-4669-a4f8-128bae683fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnvalCommPlan&quot;)</value>
      <webElementGuid>659f1a04-734b-433d-ae28-0c53616dbd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  I_7457cf/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>a2013c9d-8110-463f-a42f-f8c7b46c892a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='btnvalCommPlan']</value>
      <webElementGuid>13732b4e-1a82-4d1b-98e5-50b85b3db630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CA024']/table/tbody/tr[5]/td[2]/table/tbody/tr/td/a/img</value>
      <webElementGuid>636d0756-fa1e-488b-81c2-2706ea51890e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Código del plan de comisiones de la póliza o certificado (Valores posibles)']</value>
      <webElementGuid>cb1564e0-3ed7-473e-9d1f-47d6ccb18fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5ad4595d-eed0-4e20-8feb-ac5d30b6058a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://ori-dtp-vtimeos.retiro.ar:8083/VTimeNet/images/btn_ValuesOn.png' and @name = 'btnvalCommPlan' and @id = 'btnvalCommPlan' and @alt = 'Código del plan de comisiones de la póliza o certificado (Valores posibles)' and @title = 'Código del plan de comisiones de la póliza o certificado (Valores posibles)']</value>
      <webElementGuid>3e525555-b80b-4339-9b7f-dcc1ea5aca99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
