<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ComisinfijaEstructuradegestinNoPoseeComisionSegntabla</name>
   <tag></tag>
   <elementGuidId>37ea7c9b-88c8-48de-ac2a-74401cf309f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;cbeType&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='cbeType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>464d4e34-39bd-4538-a905-b516d04b8e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>80ccc11c-f61a-4696-a5db-106061ec5cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbeType</value>
      <webElementGuid>505860b8-aabc-4eb0-b6d5-3d7acfb39d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>56298777-17b4-4e48-8c6a-3547ae415471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ReloadPage()</value>
      <webElementGuid>c0f7a723-7a3d-4b28-bcb2-9c95b1b776b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comisión fijaEstructura de gestiónNo Posee ComisionSegún tabla</value>
      <webElementGuid>e4c37e6e-a9b5-4655-b05a-11d1ed87e5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CA024&quot;)/table[1]/tbody[1]/tr[3]/td[2]/select[1]</value>
      <webElementGuid>8496ebc4-72f5-4c31-b3ab-a8af5c0eba90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  I_7457cf/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>e7c63cdf-9acd-4772-bf0d-b174e682ffba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='cbeType']</value>
      <webElementGuid>8df7ad22-747b-4ec3-8f34-fceee5c8b42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CA024']/table/tbody/tr[3]/td[2]/select</value>
      <webElementGuid>2ad2dc53-3906-440b-ab30-a4f10e9e8131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo'])[1]/following::select[1]</value>
      <webElementGuid>385fb4fa-3ea8-4080-af16-aee2ca5680d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intermediarios de la póliza'])[1]/following::select[1]</value>
      <webElementGuid>eaffa761-a98a-4b71-8b1a-1c20820a5b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intermediarios permitidos'])[1]/preceding::select[1]</value>
      <webElementGuid>cbafae39-f3ea-469a-8530-9135fc8f2d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plan de comisión'])[1]/preceding::select[1]</value>
      <webElementGuid>be763f69-8f04-425f-a7bf-045ae04c0a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4905e3c5-90c1-4fb1-aa43-485cfa5ffaf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cbeType' and (text() = 'Comisión fijaEstructura de gestiónNo Posee ComisionSegún tabla' or . = 'Comisión fijaEstructura de gestiónNo Posee ComisionSegún tabla')]</value>
      <webElementGuid>785ec47d-03c4-499d-b09e-616bb37ba92f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
