<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_BODY            PEsta pgina utiliza f_a3efde</name>
   <tag></tag>
   <elementGuidId>d32de846-89cb-42e6-857e-8005630dfd46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;fraFolder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='fraFolder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>551f5702-94dc-4eb0-afe8-49001e6abe50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fraFolder</value>
      <webElementGuid>09af72e5-f644-4590-a2ff-f5cfa34569c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Blank.aspx</value>
      <webElementGuid>4ab24839-b7f4-4fc0-ba0e-6b8312e294d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[2]/frame[2]</value>
      <webElementGuid>6c456698-134b-452e-bd5d-1cf051fd90ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='fraFolder']</value>
      <webElementGuid>0ec27125-a7d5-410f-ad57-eca8a1350901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset[2]/frame[2]</value>
      <webElementGuid>f22cfc5c-80e3-4efc-98f6-df92afc6291d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'fraFolder' and @src = 'Blank.aspx']</value>
      <webElementGuid>f310274f-cd7b-4356-bbed-a4018bd7f348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
