<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cdigo postal_valZipCode</name>
   <tag></tag>
   <elementGuidId>b1a233e4-a2a8-4da9-b023-b286d256625e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;valZipCode&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='valZipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d06d7590-5d78-4e44-b244-996905c300ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>8f94180e-4ec8-4cc6-844c-00fda0172c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>valZipCode</value>
      <webElementGuid>e34bef54-820e-43f5-b736-3421c6e067ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>2d26aa86-401e-4ac1-8add-3cb146df717b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ab1cbcea-838f-49b8-92ca-165a6dae011d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>41001ee0-f89d-405e-a27a-215e8e63caba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Código postal asociada a la dirección</value>
      <webElementGuid>14ef631b-b46c-4caf-af99-18fd17acc6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>self.document.forms[0].valZipCode.HolePlace='05'; self.document.forms[0].valZipCode.IsReq=0; self.document.forms[0].valZipCode.ShowThousand=0; self.document.forms[0].valZipCode.Alias='Código postal asociada a la dirección'; self.document.forms[0].valZipCode.DecimalPlace=00;if(ValNumber(this,'.',',','false',0)){ShowValues(this,true,true,false);insOnChangeZipCode(this);}</value>
      <webElementGuid>6d14ffa2-330e-404c-91d7-3ecf6aa68a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[1]/tbody[1]/tr[7]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>3f4f665a-5bc0-4043-a85c-959841f67bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  D_07a0ec/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>02614886-afd2-4309-8d8b-89b9c34ea9ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='valZipCode']</value>
      <webElementGuid>428ba2b6-94c0-415b-9ed4-55f8770f2307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[7]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>594c883a-f3ef-4646-a563-15727836a725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>16eea726-d064-495c-b1c9-d294ade071c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'valZipCode' and @title = 'Código postal asociada a la dirección']</value>
      <webElementGuid>359e712c-e3a2-4401-a16b-7cedddbf860a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
