<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero_tctBuild</name>
   <tag></tag>
   <elementGuidId>65cf7e1d-5dad-43dd-ab42-9b49c831c3ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tctBuild&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tctBuild']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>756aa221-bbb5-4018-9eba-4592f413cfe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>TEXT</value>
      <webElementGuid>bf237321-acf9-431c-bfed-aec532fa739c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tctBuild</value>
      <webElementGuid>23dd7e0d-87da-49c0-85da-b4b756f044a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>3c82be8d-3949-40f4-9e43-4534113196c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0a782725-e88e-4a72-b3b1-4463ad73d47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>91b4cfed-be64-45eb-ac43-3fdf7cc08179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Número de estructura de la dirección</value>
      <webElementGuid>5d11d642-61e3-4fa5-87a8-1bbca2df4a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>tctBuild.IsReq=0;tctBuild.Alias=&quot;Número de estructura de la dirección&quot;;tctBuild.Maxlength=10;if(ValText(tctBuild,&quot;&quot;,&quot;False&quot;)){insChangeAddress();;}</value>
      <webElementGuid>e1b0a489-3ac8-4bdb-b546-047203ea493f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[1]/tbody[1]/tr[2]/td[2]/input[1]</value>
      <webElementGuid>e9c8113e-6a48-4e5d-918d-783477fb70e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  D_07a0ec/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>ddeb4cfe-6e06-47f4-be55-144223de9be7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tctBuild']</value>
      <webElementGuid>4612c6a3-84f9-468a-ad02-cfe1b088d36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>dfacefbd-62d0-4e4e-9f32-46160ef6ed47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>87b3c7ea-a90c-493a-9d86-d3dffe80f341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'TEXT' and @name = 'tctBuild' and @title = 'Número de estructura de la dirección']</value>
      <webElementGuid>d8097009-6832-4625-ab11-1b30675d3848</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
