<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NoquiereinformarNotiene</name>
   <tag></tag>
   <elementGuidId>fbba4907-1985-4be1-92c2-f56bae93449b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;cbeNoInformEmail&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='cbeNoInformEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>25cdf5f0-012c-43c1-94cd-c979e634aac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>19032b62-1373-4ef5-9972-0ca7ced09de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbeNoInformEmail</value>
      <webElementGuid>9d6142a3-15b8-45aa-bf6a-e1d8abb4f6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>11d16139-7bad-4c67-a52c-7914fdabbeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Causa por la cual el cliente no quiere informar dirección de correo electrónico asociada a la dirección</value>
      <webElementGuid>b3cbe9d4-890e-4c7a-b28b-bff884f0c0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>insEnableEmail(this)</value>
      <webElementGuid>1a9d229e-eea3-4100-9013-7ac9af66f45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No quiere informarNo tiene</value>
      <webElementGuid>ae38ba4a-60c9-418f-82ef-0e020ec300d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FORM&quot;)/table[1]/tbody[1]/tr[8]/td[2]/select[1]</value>
      <webElementGuid>855cbbca-44af-4e17-ab1c-6161d1fe04a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Tratamiento de plizas (Company ABC)  D_07a0ec/frame_BODY            PEsta pgina utiliza f_a3efde</value>
      <webElementGuid>bea9e9e2-c80d-4e81-af0a-fe253ea49312</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='cbeNoInformEmail']</value>
      <webElementGuid>fc00c9eb-09cb-45f4-b912-4a66888e724b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FORM']/table/tbody/tr[8]/td[2]/select</value>
      <webElementGuid>a2a7171c-61a7-4ad7-aa9e-5abb48d5755c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Causa para no indicar E-mail'])[1]/following::select[1]</value>
      <webElementGuid>3727b635-b346-4636-b5b0-22d754438d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIUDAD AUTONOMA DE BUENOS AIRE'])[2]/following::select[1]</value>
      <webElementGuid>4f2b1dbf-93a8-476c-87ff-314035c20b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[1]/preceding::select[1]</value>
      <webElementGuid>a0ab9277-791f-4fc5-bfd3-7b445ff4aeeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coordenadas'])[1]/preceding::select[1]</value>
      <webElementGuid>4bd7ab7c-dc4a-49db-83a0-1e1718ede011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/select</value>
      <webElementGuid>3b80c0c7-7ad3-4d33-90ed-0f492b62d193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cbeNoInformEmail' and @title = 'Causa por la cual el cliente no quiere informar dirección de correo electrónico asociada a la dirección' and (text() = 'No quiere informarNo tiene' or . = 'No quiere informarNo tiene')]</value>
      <webElementGuid>9d94fe47-2802-41f9-ad01-b5eb7984de5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
